In [ ]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.8 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [ ]:
# ==============================
# Scraping Ulasan Bus Simulator Indonesia (com.maleo.bussimulatorid)
# Target: 10.000 ulasan relevan dengan fitur utama
# Periode: 2020–2025
# Bahasa: Indonesia
# ==============================

from google_play_scraper import reviews, Sort
import pandas as pd
from datetime import datetime
import time

# ---------- PARAMETER ----------
APP_ID = 'com.maleo.bussimulatorid'
TARGET_COUNT = 10000  # target jumlah ulasan relevan
LANG = 'id'
COUNTRY = 'id'

# ---------- FITUR UTAMA YANG AKAN DICARI DALAM ULASAN ----------
KEYWORDS = [
    # Desain dan livery
    'livery', 'desain', 'cat bus', 'warna bus',

    # Suasana jalanan dan trayek
    'jalanan', 'trayek', 'rute', 'jalur', 'kota', 'desa',

    # PO Bus dan kendaraan lokal
    'po bus', 'bus asli', 'bus indonesia', 'kendaraan', 'sasis', 'mesin',

    # Kualitas grafis dan tampilan visual
    'grafis', 'visual', 'tampilan', 'detail',

    # Multiplayer dan konvoi
    'konvoi', 'multiplayer', 'online',

    # Suara klakson telolet
    'telolet', 'klakson',

    # Mod kendaraan
    'mod', 'modifikasi',

    # Penyimpanan dan fitur save
    'penyimpanan', 'save', 'otomatis',

    # Iklan dan banner
    'iklan', 'banner', 'tanpa iklan'
]

# ---------- BATAS WAKTU ----------
START_DATE = datetime(2020, 1, 1)
END_DATE = datetime(2025, 12, 31)

# ---------- PROSES SCRAPING ----------
all_relevant_reviews = []
token = None

print("Mulai scraping ulasan relevan...")

def is_relevant(text):
    return any(keyword in text for keyword in KEYWORDS)

while len(all_relevant_reviews) < TARGET_COUNT:
    result, token = reviews(
        APP_ID,
        lang=LANG,
        country=COUNTRY,
        sort=Sort.NEWEST,
        count=200,
        continuation_token=token
    )

    # Konversi ke DataFrame sementara
    df_temp = pd.DataFrame(result)
    df_temp['at'] = pd.to_datetime(df_temp['at'])
    df_temp['content'] = df_temp['content'].astype(str).str.lower()

    # Filter waktu dan keyword
    df_temp = df_temp[
        (df_temp['at'] >= START_DATE) &
        (df_temp['at'] <= END_DATE) &
        (df_temp['content'].apply(is_relevant))
    ]

    all_relevant_reviews.extend(df_temp.to_dict('records'))

    print(f"Total relevan sementara: {len(all_relevant_reviews)} ulasan...")

    if not token:
        print("Token habis (semua ulasan sudah diambil).")
        break

    time.sleep(1)

# ---------- BATASI HINGGA 10.000 SAJA ----------
df_final = pd.DataFrame(all_relevant_reviews).head(TARGET_COUNT)

# ---------- SIMPAN KE FILE ----------
df_final.to_csv('ulasan_bus_simulator_2020_2025_filtered_10000.csv', index=False, encoding='utf-8-sig')

print(f"\n✅ Selesai! Total {len(df_final)} ulasan relevan disimpan ke 'ulasan_bus_simulator_2020_2025_filtered_10000.csv'")

Mulai scraping ulasan relevan...
Total relevan sementara: 52 ulasan...
Total relevan sementara: 105 ulasan...
Total relevan sementara: 161 ulasan...
Total relevan sementara: 216 ulasan...
Total relevan sementara: 282 ulasan...
Total relevan sementara: 352 ulasan...
Total relevan sementara: 417 ulasan...
Total relevan sementara: 479 ulasan...
Total relevan sementara: 540 ulasan...
Total relevan sementara: 586 ulasan...
Total relevan sementara: 634 ulasan...
Total relevan sementara: 693 ulasan...
Total relevan sementara: 753 ulasan...
Total relevan sementara: 813 ulasan...
Total relevan sementara: 878 ulasan...
Total relevan sementara: 933 ulasan...
Total relevan sementara: 989 ulasan...
Total relevan sementara: 1052 ulasan...
Total relevan sementara: 1116 ulasan...
Total relevan sementara: 1169 ulasan...
Total relevan sementara: 1234 ulasan...
Total relevan sementara: 1301 ulasan...
Total relevan sementara: 1378 ulasan...
Total relevan sementara: 1445 ulasan...
Total relevan sementara: 1505 ulasan...
Total relevan sementara: 1564 ulasan...
Total relevan sementara: 1615 ulasan...
Total relevan sementara: 1673 ulasan...
Total relevan sementara: 1736 ulasan...
Total relevan sementara: 1788 ulasan...
Total relevan sementara: 1843 ulasan...
Total relevan sementara: 1893 ulasan...
Total relevan sementara: 1948 ulasan...
Total relevan sementara: 2005 ulasan...
Total relevan sementara: 2063 ulasan...
Total relevan sementara: 2104 ulasan...
Total relevan sementara: 2163 ulasan...
Total relevan sementara: 2222 ulasan...
Total relevan sementara: 2280 ulasan...
Total relevan sementara: 2344 ulasan...
Total relevan sementara: 2400 ulasan...
Total relevan sementara: 2457 ulasan...
Total relevan sementara: 2511 ulasan...
Total relevan sementara: 2572 ulasan...
Total relevan sementara: 2628 ulasan...
Total relevan sementara: 2680 ulasan...
Total relevan sementara: 2735 ulasan...
Total relevan sementara: 2798 ulasan...
Total relevan sementara: 2843 ulasan...
Total relevan sementara: 2896 ulasan...
Total relevan sementara: 2955 ulasan...
Total relevan sementara: 2999 ulasan...
Total relevan sementara: 3048 ulasan...
Total relevan sementara: 3090 ulasan...
Total relevan sementara: 3137 ulasan...
Total relevan sementara: 3169 ulasan...
Total relevan sementara: 3210 ulasan...
Total relevan sementara: 3250 ulasan...
Total relevan sementara: 3297 ulasan...
Total relevan sementara: 3353 ulasan...
Total relevan sementara: 3410 ulasan...
Total relevan sementara: 3474 ulasan...
Total relevan sementara: 3548 ulasan...
Total relevan sementara: 3607 ulasan...
Total relevan sementara: 3665 ulasan...
Total relevan sementara: 3715 ulasan...
Total relevan sementara: 3766 ulasan...
Total relevan sementara: 3821 ulasan...
Total relevan sementara: 3876 ulasan...
Total relevan sementara: 3929 ulasan...
Total relevan sementara: 3984 ulasan...
Total relevan sementara: 4042 ulasan...
Total relevan sementara: 4111 ulasan...
Total relevan sementara: 4162 ulasan...
Total relevan sementara: 4219 ulasan...
Total relevan sementara: 4280 ulasan...
Total relevan sementara: 4347 ulasan...
Total relevan sementara: 4401 ulasan...
Total relevan sementara: 4456 ulasan...
Total relevan sementara: 4500 ulasan...
Total relevan sementara: 4558 ulasan...
Total relevan sementara: 4609 ulasan...
Total relevan sementara: 4675 ulasan...
Total relevan sementara: 4732 ulasan...
Total relevan sementara: 4795 ulasan...
Total relevan sementara: 4854 ulasan...
Total relevan sementara: 4909 ulasan...
Total relevan sementara: 4959 ulasan...
Total relevan sementara: 5018 ulasan...
Total relevan sementara: 5071 ulasan...
Total relevan sementara: 5127 ulasan...
Total relevan sementara: 5196 ulasan...
Total relevan sementara: 5244 ulasan...
Total relevan sementara: 5290 ulasan...
Total relevan sementara: 5349 ulasan...
Total relevan sementara: 5401 ulasan...
Total relevan sementara: 5464 ulasan...
Total relevan sementara: 5516 ulasan...
Total relevan sementara: 5584 ulasan...
Total relevan sementara: 5642 ulasan...
Total relevan sementara: 5709 ulasan...
Total relevan sementara: 5761 ulasan...
Total relevan sementara: 5822 ulasan...
Total relevan sementara: 5879 ulasan...
Total relevan sementara: 5926 ulasan...
Total relevan sementara: 5974 ulasan...
Total relevan sementara: 6018 ulasan...
Total relevan sementara: 6076 ulasan...
Total relevan sementara: 6131 ulasan...
Total relevan sementara: 6189 ulasan...
Total relevan sementara: 6243 ulasan...
Total relevan sementara: 6298 ulasan...
Total relevan sementara: 6351 ulasan...
Total relevan sementara: 6403 ulasan...
Total relevan sementara: 6456 ulasan...
Total relevan sementara: 6498 ulasan...
Total relevan sementara: 6546 ulasan...
Total relevan sementara: 6593 ulasan...
Total relevan sementara: 6642 ulasan...
Total relevan sementara: 6699 ulasan...
Total relevan sementara: 6752 ulasan...
Total relevan sementara: 6811 ulasan...
Total relevan sementara: 6873 ulasan...
Total relevan sementara: 6909 ulasan...
Total relevan sementara: 6957 ulasan...
Total relevan sementara: 7005 ulasan...
Total relevan sementara: 7061 ulasan...
Total relevan sementara: 7115 ulasan...
Total relevan sementara: 7158 ulasan...
Total relevan sementara: 7209 ulasan...
Total relevan sementara: 7266 ulasan...
Total relevan sementara: 7320 ulasan...
Total relevan sementara: 7363 ulasan...
Total relevan sementara: 7413 ulasan...
Total relevan sementara: 7466 ulasan...
Total relevan sementara: 7522 ulasan...
Total relevan sementara: 7578 ulasan...
Total relevan sementara: 7631 ulasan...
Total relevan sementara: 7680 ulasan...
Total relevan sementara: 7729 ulasan...
Total relevan sementara: 7771 ulasan...
Total relevan sementara: 7796 ulasan...
Total relevan sementara: 7847 ulasan...
Total relevan sementara: 7901 ulasan...
Total relevan sementara: 7943 ulasan...
Total relevan sementara: 7991 ulasan...
Total relevan sementara: 8037 ulasan...
Total relevan sementara: 8076 ulasan...
Total relevan sementara: 8126 ulasan...
Total relevan sementara: 8186 ulasan...
Total relevan sementara: 8242 ulasan...
Total relevan sementara: 8274 ulasan...
Total relevan sementara: 8331 ulasan...
Total relevan sementara: 8377 ulasan...
Total relevan sementara: 8432 ulasan...
Total relevan sementara: 8488 ulasan...
Total relevan sementara: 8532 ulasan...
Total relevan sementara: 8584 ulasan...
Total relevan sementara: 8644 ulasan...
Total relevan sementara: 8699 ulasan...
Total relevan sementara: 8757 ulasan...
Total relevan sementara: 8801 ulasan...
Total relevan sementara: 8859 ulasan...
Total relevan sementara: 8906 ulasan...
Total relevan sementara: 8967 ulasan...
Total relevan sementara: 9016 ulasan...
Total relevan sementara: 9062 ulasan...
Total relevan sementara: 9111 ulasan...
Total relevan sementara: 9161 ulasan...
Total relevan sementara: 9212 ulasan...
Total relevan sementara: 9263 ulasan...
Total relevan sementara: 9315 ulasan...
Total relevan sementara: 9366 ulasan...
Total relevan sementara: 9426 ulasan...
Total relevan sementara: 9481 ulasan...
Total relevan sementara: 9540 ulasan...
Total relevan sementara: 9600 ulasan...
Total relevan sementara: 9643 ulasan...
Total relevan sementara: 9682 ulasan...
Total relevan sementara: 9738 ulasan...
Total relevan sementara: 9779 ulasan...
Total relevan sementara: 9826 ulasan...
Total relevan sementara: 9875 ulasan...
Total relevan sementara: 9925 ulasan...
Total relevan sementara: 9977 ulasan...
Total relevan sementara: 10014 ulasan...

✅ Selesai! Total 10000 ulasan relevan disimpan ke 'ulasan_bus_simulator_2020_2025_filtered_10000.csv'

In [ ]:
# ==============================
# Scraping Ulasan Bus Simulator Indonesia (com.maleo.bussimulatorid)
# Target: 6.000 ulasan relevan (2020–2025)
# Distribusi: ~1.000 ulasan per tahun
# Bahasa: Indonesia
# ==============================

from google_play_scraper import reviews, Sort
import pandas as pd
from datetime import datetime
import time
import math

# ---------- PARAMETER ----------
APP_ID = 'com.maleo.bussimulatorid'
TARGET_TOTAL = 6000           # total target semua tahun
LANG = 'id'
COUNTRY = 'id'

# ---------- FITUR UTAMA ----------
KEYWORDS = [
    'livery', 'desain', 'cat bus', 'warna bus',
    'jalanan', 'trayek', 'rute', 'jalur', 'kota', 'desa',
    'po bus', 'bus asli', 'bus indonesia', 'kendaraan', 'sasis', 'mesin',
    'grafis', 'visual', 'tampilan', 'detail',
    'konvoi', 'multiplayer', 'online',
    'telolet', 'klakson',
    'mod', 'modifikasi',
    'penyimpanan', 'save', 'otomatis',
    'iklan', 'banner', 'tanpa iklan'
]

# ---------- PERIODE ----------
YEARS = [2020, 2021, 2022, 2023, 2024, 2025]
PER_YEAR_TARGET = math.floor(TARGET_TOTAL / len(YEARS))  # ~1667 per tahun

# ---------- FUNGSI FILTER ----------
def is_relevant(text):
    text = text.lower()
    return any(keyword in text for keyword in KEYWORDS)

# ---------- PROSES SCRAPING ----------
all_reviews = []

print("🚀 Mulai scraping ulasan relevan per tahun (2020–2025)...\n")

for year in YEARS:
    print(f"📅 Mengambil ulasan tahun {year}...")
    year_reviews = []
    token = None

    start_date = datetime(year, 1, 1)
    end_date = datetime(year, 12, 31)

    while len(year_reviews) < PER_YEAR_TARGET:
        result, token = reviews(
            APP_ID,
            lang=LANG,
            country=COUNTRY,
            sort=Sort.NEWEST,
            count=200,
            continuation_token=token
        )

        # Konversi ke DataFrame
        df_temp = pd.DataFrame(result)
        df_temp['at'] = pd.to_datetime(df_temp['at'])
        df_temp['content'] = df_temp['content'].astype(str).str.lower()

        # Filter tahun dan relevansi
        df_temp = df_temp[
            (df_temp['at'] >= start_date) &
            (df_temp['at'] <= end_date) &
            (df_temp['content'].apply(is_relevant))
        ]

        # Tambah ke kumpulan tahun
        year_reviews.extend(df_temp.to_dict('records'))

        print(f"   ↳ {len(year_reviews)} ulasan relevan terkumpul ({year})...")

        if not token:
            print(f"⚠️ Token habis untuk tahun {year}, hanya {len(year_reviews)} ulasan yang tersedia.")
            break

        time.sleep(1)  # jeda antar request

    # Batasi sesuai target tahunan
    df_year = pd.DataFrame(year_reviews).head(PER_YEAR_TARGET)
    all_reviews.extend(df_year.to_dict('records'))

    print(f"✅ Tahun {year} selesai ({len(df_year)} ulasan diambil)\n")
    time.sleep(2)

# ---------- GABUNGKAN DAN SIMPAN ----------
df_final = pd.DataFrame(all_reviews).head(TARGET_TOTAL)
df_final.to_csv('ulasan_bus_simulator_2020_2025_filtered_equal_6000.csv', index=False, encoding='utf-8-sig')

print(f"\n🎯 Selesai! Total {len(df_final)} ulasan relevan (≈1.000 per tahun) disimpan ke 'ulasan_bus_simulator_2020_2025_filtered_equal_10000.csv'")

Streaming output truncated to the last 5000 lines.
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...
   ↳ 0 ulasan relevan terkumpul (2020)...

In [ ]:
# ==============================
# Scraping Ulasan Bus Simulator Indonesia (com.maleo.bussimulatorid)
# Periode: 2021–2025 (semua ulasan relevan)
# Bahasa: Indonesia
# ==============================

from google_play_scraper import reviews, Sort
import pandas as pd
from datetime import datetime
import time

# ---------- PARAMETER ----------
APP_ID = 'com.maleo.bussimulatorid'
LANG = 'id'
COUNTRY = 'id'

# ---------- FITUR UTAMA ----------
KEYWORDS = [
    'livery', 'desain', 'cat bus', 'warna bus',
    'jalanan', 'trayek', 'rute', 'jalur', 'kota', 'desa',
    'po bus', 'bus asli', 'bus indonesia', 'kendaraan', 'sasis', 'mesin',
    'grafis', 'visual', 'tampilan', 'detail',
    'konvoi', 'multiplayer', 'online',
    'telolet', 'klakson',
    'mod', 'modifikasi',
    'penyimpanan', 'save', 'otomatis',
    'iklan', 'banner', 'tanpa iklan'
]

# ---------- PERIODE ----------
YEARS = [2021, 2022, 2023, 2024, 2025]

# ---------- FUNGSI FILTER ----------
def is_relevant(text):
    text = text.lower()
    return any(keyword in text for keyword in KEYWORDS)

# ---------- PROSES SCRAPING ----------
all_reviews = []

print("🚀 Mulai scraping semua ulasan relevan (2021–2025)...\n")

token = None
finished = False

while not finished:
    result, token = reviews(
        APP_ID,
        lang=LANG,
        country=COUNTRY,
        sort=Sort.NEWEST,
        count=200,
        continuation_token=token
    )

    if not result:
        break

    df_temp = pd.DataFrame(result)
    df_temp['at'] = pd.to_datetime(df_temp['at'])
    df_temp['content'] = df_temp['content'].astype(str).str.lower()

    # Filter tahun 2021–2025
    df_temp = df_temp[
        (df_temp['at'].dt.year >= 2021) &
        (df_temp['at'].dt.year <= 2025)
    ]

    # Filter relevansi keyword
    df_temp = df_temp[df_temp['content'].apply(is_relevant)]

    # Simpan
    all_reviews.extend(df_temp.to_dict('records'))

    print(f"📌 Total sementara: {len(all_reviews)} ulasan relevan...")

    if not token:
        finished = True

    time.sleep(1)

print("\n⏳ Scraping selesai, memproses data...")

# ---------- SIMPAN ----------
df_final = pd.DataFrame(all_reviews)
df_final.to_csv('ulasan_bus_simulator_2021_2025_filtered_full.csv', index=False, encoding='utf-8-sig')

print(f"\n🎯 Selesai! Total {len(df_final)} ulasan relevan telah disimpan ke:")
print("➡️  'ulasan_bus_simulator_2021_2025_filtered_full.csv'")

🚀 Mulai scraping semua ulasan relevan (2021–2025)...

📌 Total sementara: 62 ulasan relevan...
📌 Total sementara: 128 ulasan relevan...
📌 Total sementara: 189 ulasan relevan...
📌 Total sementara: 240 ulasan relevan...
📌 Total sementara: 299 ulasan relevan...
📌 Total sementara: 366 ulasan relevan...
📌 Total sementara: 425 ulasan relevan...
📌 Total sementara: 492 ulasan relevan...
📌 Total sementara: 549 ulasan relevan...
📌 Total sementara: 622 ulasan relevan...

KeyboardInterrupt:

In [ ]:
import pandas as pd

df = pd.read_csv('/content/ulasan_bus_simulator_2021_2025_filtered_full.csv')
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,1b109463-be6b-44f5-965d-58eeb6e2dd77,avil ramadani,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong di perbaiki bug nya pasang mod tidak bisa,5,0,4.4.1,2025-11-28 00:22:06,NaN,NaN,4.4.1
1,5a4bafa0-ff3c-4149-b0a8-d31711969e45,Daffa Irmansyah,https://play-lh.googleusercontent.com/a/ACg8oc...,bang tolong tambahin bus sddnya sama tambain k...,5,0,2.6,2025-11-27 17:16:32,NaN,NaN,2.6
2,e63ec1ff-b277-4fcf-b6c1-18096554f13f,Fikri Eka Wicaksono,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong maleo kasih fitur untuk mabar pake mod ...,5,0,4.4.1,2025-11-27 16:34:15,NaN,NaN,4.4.1
3,f4b5f5ce-844a-494f-940f-e62a1168939d,Alfan Dm,https://play-lh.googleusercontent.com/a/ACg8oc...,memang bagus dan grafik nya juga keren cuman y...,1,0,NaN,2025-11-27 16:09:18,NaN,NaN,NaN
4,c579f605-685f-48b7-ab7b-2d2c1322b259,Aku uwong Saya orang,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong lah hapus tuh iklan judol,1,0,4.4.1,2025-11-27 15:34:19,NaN,NaN,4.4.1
...,...,...,...,...,...,...,...,...,...,...,...
97289,e5fb3857-dd92-4d7e-9e9e-2253cf90ffdb,Ahmad Dani,https://play-lh.googleusercontent.com/a-/ALV-U...,game nya bisa mod apa aja,5,0,NaN,2021-01-01 01:18:25,NaN,NaN,NaN
97290,24bd5ea6-b6c2-4623-81f6-281d9761bdd1,Imam Jakfar,https://play-lh.googleusercontent.com/a/ACg8oc...,"game nya udah bagu ,min tolong turunin dong mb...",5,1,3.4.3,2021-01-01 00:37:58,NaN,NaN,3.4.3
97291,952e1ec9-11b2-46b1-964e-c6d54c7834db,rahman official,https://play-lh.googleusercontent.com/a-/ALV-U...,mohon bussid tolong kalo narik kita dari garas...,5,0,3.3.2,2021-01-01 00:19:07,NaN,NaN,3.3.2
97292,7b0a5c8f-2e2d-4249-b6a0-1cfcbe174151,Syafina & Kenzie,https://play-lh.googleusercontent.com/a-/ALV-U...,"gem ya, bisapake mod truck new bekaje biar tam...",5,0,3.4.3,2021-01-01 00:18:10,NaN,NaN,3.4.3
97293,fadf0fec-0826-4fb4-8655-32e694296b47,Iko Prastiyo,https://play-lh.googleusercontent.com/a-/ALV-U...,masih kalah jauh dengan euro truck simulator 2...,1,0,3.3.3,2021-01-01 00:16:22,NaN,NaN,3.3.3

In [ ]:
import pandas as pd

# ==============================
# BACA DATA SCRAPING
# ==============================
df = pd.read_csv('/content/ulasan_bus_simulator_2021_2025_filtered_full.csv')

# Pastikan tanggal dibaca dengan benar
df['at'] = pd.to_datetime(df['at'])

# ==============================
# BUAT KOLOM YEAR (YYYY)
# ==============================
df['year'] = df['at'].dt.year

# ==============================
# HITUNG JUMLAH ULASAN PER TAHUN
# ==============================
yearly_count = df.groupby('year').size().reset_index(name='jumlah_ulasan')

# ==============================
# SIMPAN HASIL
# ==============================
yearly_count.to_csv('jumlah_ulasan_pertahun_2021_2025.csv', index=False, encoding='utf-8-sig')

print("📊 Rekap jumlah ulasan per tahun telah disimpan ke:")
print("➡️  jumlah_ulasan_pertahun_2021_2025.csv")

# Tampilkan output
yearly_count

📊 Rekap jumlah ulasan per tahun telah disimpan ke:
➡️  jumlah_ulasan_pertahun_2021_2025.csv

   year  jumlah_ulasan
0  2021          32584
1  2022          20818
2  2023          18396
3  2024          14774
4  2025          10722

In [ ]:
import pandas as pd

# ==============================
# BACA DATA SCRAPING
# ==============================
df = pd.read_csv('/content/ulasan_bus_simulator_2021_2025_filtered_full.csv')

# Pastikan tanggal dibaca dengan benar
df['at'] = pd.to_datetime(df['at'])

# ==============================
# BUAT KOLOM YEAR-MONTH (YYYY-MM)
# ==============================
df['year_month'] = df['at'].dt.to_period('M').astype(str)

# ==============================
# HITUNG JUMLAH ULASAN PER BULAN
# ==============================
monthly_count = df.groupby('year_month').size().reset_index(name='jumlah_ulasan')

# ==============================
# SIMPAN HASIL
# ==============================
monthly_count.to_csv('jumlah_ulasan_perbulan_2021_2025.csv', index=False, encoding='utf-8-sig')

print("📊 Rekap jumlah ulasan per bulan telah disimpan ke:")
print("➡️  jumlah_ulasan_perbulan_2021_2025.csv")

# Tampilkan 20 baris pertama
monthly_count.head(60)

📊 Rekap jumlah ulasan per bulan telah disimpan ke:
➡️  jumlah_ulasan_perbulan_2021_2025.csv

   year_month  jumlah_ulasan
0     2021-01           4813
1     2021-02           2997
2     2021-03           3029
3     2021-04           2538
4     2021-05           2129
5     2021-06           4163
6     2021-07           3213
7     2021-08           2282
8     2021-09           1819
9     2021-10           1810
10    2021-11           1662
11    2021-12           2129
12    2022-01           2132
13    2022-02           1416
14    2022-03           1411
15    2022-04           1829
16    2022-05           1615
17    2022-06           1876
18    2022-07           1865
19    2022-08           3423
20    2022-09           1598
21    2022-10           1274
22    2022-11            990
23    2022-12           1389
24    2023-01           1078
25    2023-02            856
26    2023-03           1135
27    2023-04           1019
28    2023-05           1008
29    2023-06            938
30    2023-07           1009
31    2023-08            628
32    2023-09            650
33    2023-10           5943
34    2023-11           2178
35    2023-12           1954
36    2024-01           1773
37    2024-02           1302
38    2024-03           1538
39    2024-04           1102
40    2024-05           1062
41    2024-06           1330
42    2024-07           1112
43    2024-08           1294
44    2024-09           1041
45    2024-10            912
46    2024-11            881
47    2024-12           1427
48    2025-01           1143
49    2025-02            767
50    2025-03           1139
51    2025-04            904
52    2025-05           1140
53    2025-06            961
54    2025-07           1234
55    2025-08            818
56    2025-09            803
57    2025-10            882
58    2025-11            931

In [ ]:
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,year_month
0,1b109463-be6b-44f5-965d-58eeb6e2dd77,avil ramadani,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong di perbaiki bug nya pasang mod tidak bisa,5,0,4.4.1,2025-11-28 00:22:06,NaN,NaN,4.4.1,2025-11
1,5a4bafa0-ff3c-4149-b0a8-d31711969e45,Daffa Irmansyah,https://play-lh.googleusercontent.com/a/ACg8oc...,bang tolong tambahin bus sddnya sama tambain k...,5,0,2.6,2025-11-27 17:16:32,NaN,NaN,2.6,2025-11
2,e63ec1ff-b277-4fcf-b6c1-18096554f13f,Fikri Eka Wicaksono,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong maleo kasih fitur untuk mabar pake mod ...,5,0,4.4.1,2025-11-27 16:34:15,NaN,NaN,4.4.1,2025-11
3,f4b5f5ce-844a-494f-940f-e62a1168939d,Alfan Dm,https://play-lh.googleusercontent.com/a/ACg8oc...,memang bagus dan grafik nya juga keren cuman y...,1,0,NaN,2025-11-27 16:09:18,NaN,NaN,NaN,2025-11
4,c579f605-685f-48b7-ab7b-2d2c1322b259,Aku uwong Saya orang,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong lah hapus tuh iklan judol,1,0,4.4.1,2025-11-27 15:34:19,NaN,NaN,4.4.1,2025-11
...,...,...,...,...,...,...,...,...,...,...,...,...
97289,e5fb3857-dd92-4d7e-9e9e-2253cf90ffdb,Ahmad Dani,https://play-lh.googleusercontent.com/a-/ALV-U...,game nya bisa mod apa aja,5,0,NaN,2021-01-01 01:18:25,NaN,NaN,NaN,2021-01
97290,24bd5ea6-b6c2-4623-81f6-281d9761bdd1,Imam Jakfar,https://play-lh.googleusercontent.com/a/ACg8oc...,"game nya udah bagu ,min tolong turunin dong mb...",5,1,3.4.3,2021-01-01 00:37:58,NaN,NaN,3.4.3,2021-01
97291,952e1ec9-11b2-46b1-964e-c6d54c7834db,rahman official,https://play-lh.googleusercontent.com/a-/ALV-U...,mohon bussid tolong kalo narik kita dari garas...,5,0,3.3.2,2021-01-01 00:19:07,NaN,NaN,3.3.2,2021-01
97292,7b0a5c8f-2e2d-4249-b6a0-1cfcbe174151,Syafina & Kenzie,https://play-lh.googleusercontent.com/a-/ALV-U...,"gem ya, bisapake mod truck new bekaje biar tam...",5,0,3.4.3,2021-01-01 00:18:10,NaN,NaN,3.4.3,2021-01
97293,fadf0fec-0826-4fb4-8655-32e694296b47,Iko Prastiyo,https://play-lh.googleusercontent.com/a-/ALV-U...,masih kalah jauh dengan euro truck simulator 2...,1,0,3.3.3,2021-01-01 00:16:22,NaN,NaN,3.3.3,2021-01

In [ ]:
df['content']

0         tolong di perbaiki bug nya pasang mod tidak bisa
1        bang tolong tambahin bus sddnya sama tambain k...
2        tolong maleo kasih fitur untuk mabar pake mod ...
3        memang bagus dan grafik nya juga keren cuman y...
4                         tolong lah hapus tuh iklan judol
                               ...
97289                            game nya bisa mod apa aja
97290    game nya udah bagu ,min tolong turunin dong mb...
97291    mohon bussid tolong kalo narik kita dari garas...
97292    gem ya, bisapake mod truck new bekaje biar tam...
97293    masih kalah jauh dengan euro truck simulator 2...
Name: content, Length: 97294, dtype: object

In [ ]:
pd.set_option('display.max_colwidth', None)
df['content']

0                                                                                                                                                                                                                       tolong di perbaiki bug nya pasang mod tidak bisa
1                                                                                                                                                                                                                   bang tolong tambahin bus sddnya sama tambain kotanya
2                                                                                                                                                                                                         tolong maleo kasih fitur untuk mabar pake mod deh maleo plisss
3                                                                                                                                                                memang bagus dan grafik nya juga keren cuman yang bikin masalah nya itu karna iklan loh jadi mengganggu
4                                                                                                                                                                                                                                       tolong lah hapus tuh iklan judol
                                                                                                                                      ...
97289                                                                                                                                                                                                                                          game nya bisa mod apa aja
97290    game nya udah bagu ,min tolong turunin dong mb nya kalau bisa buad mod knalpot serigala benerran tolongg nya min buad mod nya ya kalau gem nya udah bagus turunin dong mb ke 250 mb aja ya min ite4us cara nadetx gimana min saya udah 5 main kok belomabde5 ya
97291                                                                                                                                                               mohon bussid tolong kalo narik kita dari garasi ke terminal,tambahin kota lagi,saya tunggu updatenya
97292                                                                                                                                                                                                           gem ya, bisapake mod truck new bekaje biar tambah keten👍
97293                                                                                                                                                             masih kalah jauh dengan euro truck simulator 2,,,tolong donk di tingkatkan kembali grafis dan rute nya
Name: content, Length: 97294, dtype: object

In [ ]:
# 2. Hitung total jumlah data
total_data = len(df)
print("Total jumlah data:", total_data)

# 3. Hitung 20% dari total data
persen_20 = total_data * 0.20
print("Hasil 20% dari total data:", persen_20)

Total jumlah data: 97294
Hasil 20% dari total data: 19458.8

In [ ]:
import math
persen_20_bulat = math.ceil(persen_20)
print("20% dibulatkan:", persen_20_bulat)

20% dibulatkan: 19459

In [ ]:
# Pastikan tanggal dibaca dengan benar
df['at'] = pd.to_datetime(df['at'])

# ==============================
# BUAT KOLOM YEAR-MONTH (YYYY-MM)
# ==============================
df['year_month'] = df['at'].dt.to_period('M').astype(str)

# ==============================
# HITUNG JUMLAH ULASAN PER BULAN
# ==============================
monthly_count = df.groupby('year_month').size().reset_index(name='jumlah_ulasan')

# ==============================
# HITUNG 20% DARI JUMLAH ULASAN (dibulatkan)
# ==============================
monthly_count['persen_20'] = (monthly_count['jumlah_ulasan'] * 0.20).apply(math.ceil)

# ==============================
# SIMPAN HASIL LENGKAP
# ==============================
monthly_count.to_csv('jumlah_ulasan_perbulan_20persen.csv',
                     index=False, encoding='utf-8-sig')

print("📊 Rekap jumlah ulasan + 20% per bulan disimpan ke:")
print("➡️ jumlah_ulasan_perbulan_20persen.csv")

# Tampilkan 60 baris
monthly_count.head(60)

📊 Rekap jumlah ulasan + 20% per bulan disimpan ke:
➡️ jumlah_ulasan_perbulan_20persen.csv

   year_month  jumlah_ulasan  persen_20
0     2021-01           4813        963
1     2021-02           2997        600
2     2021-03           3029        606
3     2021-04           2538        508
4     2021-05           2129        426
5     2021-06           4163        833
6     2021-07           3213        643
7     2021-08           2282        457
8     2021-09           1819        364
9     2021-10           1810        362
10    2021-11           1662        333
11    2021-12           2129        426
12    2022-01           2132        427
13    2022-02           1416        284
14    2022-03           1411        283
15    2022-04           1829        366
16    2022-05           1615        323
17    2022-06           1876        376
18    2022-07           1865        373
19    2022-08           3423        685
20    2022-09           1598        320
21    2022-10           1274        255
22    2022-11            990        198
23    2022-12           1389        278
24    2023-01           1078        216
25    2023-02            856        172
26    2023-03           1135        227
27    2023-04           1019        204
28    2023-05           1008        202
29    2023-06            938        188
30    2023-07           1009        202
31    2023-08            628        126
32    2023-09            650        130
33    2023-10           5943       1189
34    2023-11           2178        436
35    2023-12           1954        391
36    2024-01           1773        355
37    2024-02           1302        261
38    2024-03           1538        308
39    2024-04           1102        221
40    2024-05           1062        213
41    2024-06           1330        266
42    2024-07           1112        223
43    2024-08           1294        259
44    2024-09           1041        209
45    2024-10            912        183
46    2024-11            881        177
47    2024-12           1427        286
48    2025-01           1143        229
49    2025-02            767        154
50    2025-03           1139        228
51    2025-04            904        181
52    2025-05           1140        228
53    2025-06            961        193
54    2025-07           1234        247
55    2025-08            818        164
56    2025-09            803        161
57    2025-10            882        177
58    2025-11            931        187

In [ ]:
# ==============================
# AMBIL DATA SESUAI JUMLAH persen_20
# ==============================

# DataFrame untuk menyimpan hasil akhir
sampled_data = pd.DataFrame()

for index, row in monthly_count.iterrows():
    ym = row['year_month']
    n_sample = row['persen_20']

    # Filter data sesuai tahun-bulan
    df_filtered = df[df['year_month'] == ym]

    # Jika sample lebih besar dari jumlah data (sangat jarang), ambil semua
    if n_sample > len(df_filtered):
        n_sample = len(df_filtered)

    # Ambil sample acak
    df_sample = df_filtered.sample(n=n_sample, random_state=42)

    # Tambahkan ke dataframe hasil
    sampled_data = pd.concat([sampled_data, df_sample], ignore_index=True)

# Simpan ke file CSV
sampled_data.to_csv("sample_ulasan_20persen_perbulan.csv", index=False, encoding="utf-8-sig")

print("✓ Data sample 20% per bulan berhasil dibuat.")
print("➡️ File: sample_ulasan_20persen_perbulan.csv")

# Tampilkan 10 baris pertama hasil
sampled_data.head(10)

✓ Data sample 20% per bulan berhasil dibuat.
➡️ File: sample_ulasan_20persen_perbulan.csv

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,year_month
0,dd3a3573-c2a3-4ffe-84e7-8fa9e003f745,M.Rizky Aziz,https://play-lh.googleusercontent.com/a-/ALV-UjVupQgERvcYWzbaaECbxNE1xFjgnIHWLLLhmewj9z8yodOcym6J,tolong adakan main bareng pake mod,4,0,3.4.3,2021-01-03 09:23:09,NaN,NaN,3.4.3,2021-01
1,0a4e2124-cb99-4615-a311-9c0ca649952a,Risfan Sya'bana (PanggilAkuSya'ban),https://play-lh.googleusercontent.com/a-/ALV-UjWHicngXa4nU0YP9WpaYMsqaSmMMOTs8YnEu4KJpXdz5ERzF8c,"bagus sih....... tapi sedikit masukan ya, tolong lah harga bus jangan mahal banget, itu aja dalam segi grafis oke, map tambahin lagi kek lumajang jember probolinggo malang banjarmasin kalimantan, itu aja plisss yah🙏",5,0,NaN,2021-01-06 06:02:56,NaN,NaN,NaN,2021-01
2,2a36e8a0-9311-4049-9feb-348db14b48d2,Vickar Renaldy,https://play-lh.googleusercontent.com/a/ACg8ocLzr7JRgwisJ2p5TaNzubyCfBfGLkT9jSaQYxqxjF3FYjxgug=mo,game nya bagus tapi masih ada yang kuran misal nya ga ada pejalan kaki terus kasih kendaraan lain nya jadi tolong ya terima kasih,5,0,NaN,2021-01-25 11:05:24,NaN,NaN,NaN,2021-01
3,56d2a53c-0968-4313-b34e-6751a78c8dd3,DAVIS Saja,https://play-lh.googleusercontent.com/a/ACg8ocJsSQKm_eSj8EAhuJ6qud6skK2s-i6dYuYjP9TRpLTQL4d2NQ=mo,tolong maelo di perbanyak lagi rute nya,5,0,NaN,2021-01-23 15:23:07,NaN,NaN,NaN,2021-01
4,1d1c8c09-a758-4eff-bbc7-3cf29ad23c79,Zwarxy XR,https://play-lh.googleusercontent.com/a-/ALV-UjUPt5cdAeMh1itgjZiRoMzXKaqzWE1jrE030yXYMfI_KyMjxZUJ,game busid masih banyak kekurangannya : 1.mobil npc ugal-ugalan 2.penumpang masuk bus langsung hilang 3.penumpang naik bis di pinggir jalan bukan di terminal 4.banyak iklan,1,0,NaN,2021-01-31 17:09:04,NaN,NaN,NaN,2021-01
5,8078f896-1920-4bdd-8513-e0e3f2fd3a3d,aulia Ikaisaira,https://play-lh.googleusercontent.com/a/ACg8ocJqr6tNnMb81pXKZ5NarDXmxK9HILvPA4WlFZFsYHl_KG6_9w=mo,bus simulator tolong di uapdet dong mod bisa di buat mabar 🙁🙁🙁🙁😭😭😭😭😭,5,0,3.4,2021-01-15 16:06:51,NaN,NaN,3.4,2021-01
6,741d9486-45db-4ebf-bb01-91bf492f7f44,arizki Ubaidillah,https://play-lh.googleusercontent.com/a/ACg8ocKFM6kRLjXyutKw4YdKy_4g0GU40kMhzaG_aLLF0V-VHiuRfw=mo,gm birik gk seru!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! tapi boong gm ini seru banget bisa maling mod orang yang ada di yutub,5,0,NaN,2021-01-08 03:59:22,NaN,NaN,NaN,2021-01
7,45b3576d-330c-4552-99a1-9ad67d6daf15,Jhon M Saragih,https://play-lh.googleusercontent.com/a-/ALV-UjXJbOpDycfBvXLjAm836QpHpNWUkYhTMDDiVYKJ71p1RDSv7Ts,"permainan seru banget..kayak asli nya... tp tolong lah di upded lg,tmbah rute nya lg soalnya itu2 ja rute nya bosan juga.. tmbahin seperti ke medan,aceh dll..kalau makin banyak rute nya kan makin lebih seru lg main nya.. terimakasih..",5,6,3.5,2021-01-29 12:28:16,NaN,NaN,3.5,2021-01
8,710b20d2-103b-4df3-a14b-6b4ae22e8019,Candra Rezky Affandi,https://play-lh.googleusercontent.com/a-/ALV-UjVMohwcXQDF7_S4FGRhUgZPepF570XLPp-S7UWRrzbzIgw7q5M,semoga update kedepan mod bissa untuk mabar,5,0,3.4.3,2021-01-12 00:13:40,NaN,NaN,3.4.3,2021-01
9,6197cd48-b95f-4f50-a137-b8bbd7e822c8,Moch dwi Cahyo S.,https://play-lh.googleusercontent.com/a/ACg8ocKueI2pbsc_J0_Vlgng_bORo2siivmdY7k4pF73dtV_VVIzZg=mo,"tolong pihak bus simulator tambahkan kota di jawa timur , jawa tengah,dan jawa barat.dan di tambahkan jalan sempit dan ada banyak perumahan di gang sempit dan banyak orang",5,0,NaN,2021-01-20 05:35:30,NaN,NaN,NaN,2021-01

In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_ulasan_20persen_perbulan.csv')
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,year_month
0,dd3a3573-c2a3-4ffe-84e7-8fa9e003f745,M.Rizky Aziz,https://play-lh.googleusercontent.com/a-/ALV-UjVupQgERvcYWzbaaECbxNE1xFjgnIHWLLLhmewj9z8yodOcym6J,tolong adakan main bareng pake mod,4,0,3.4.3,2021-01-03 09:23:09,NaN,NaN,3.4.3,2021-01
1,0a4e2124-cb99-4615-a311-9c0ca649952a,Risfan Sya'bana (PanggilAkuSya'ban),https://play-lh.googleusercontent.com/a-/ALV-UjWHicngXa4nU0YP9WpaYMsqaSmMMOTs8YnEu4KJpXdz5ERzF8c,"bagus sih....... tapi sedikit masukan ya, tolong lah harga bus jangan mahal banget, itu aja dalam segi grafis oke, map tambahin lagi kek lumajang jember probolinggo malang banjarmasin kalimantan, itu aja plisss yah🙏",5,0,NaN,2021-01-06 06:02:56,NaN,NaN,NaN,2021-01
2,2a36e8a0-9311-4049-9feb-348db14b48d2,Vickar Renaldy,https://play-lh.googleusercontent.com/a/ACg8ocLzr7JRgwisJ2p5TaNzubyCfBfGLkT9jSaQYxqxjF3FYjxgug=mo,game nya bagus tapi masih ada yang kuran misal nya ga ada pejalan kaki terus kasih kendaraan lain nya jadi tolong ya terima kasih,5,0,NaN,2021-01-25 11:05:24,NaN,NaN,NaN,2021-01
3,56d2a53c-0968-4313-b34e-6751a78c8dd3,DAVIS Saja,https://play-lh.googleusercontent.com/a/ACg8ocJsSQKm_eSj8EAhuJ6qud6skK2s-i6dYuYjP9TRpLTQL4d2NQ=mo,tolong maelo di perbanyak lagi rute nya,5,0,NaN,2021-01-23 15:23:07,NaN,NaN,NaN,2021-01
4,1d1c8c09-a758-4eff-bbc7-3cf29ad23c79,Zwarxy XR,https://play-lh.googleusercontent.com/a-/ALV-UjUPt5cdAeMh1itgjZiRoMzXKaqzWE1jrE030yXYMfI_KyMjxZUJ,game busid masih banyak kekurangannya : 1.mobil npc ugal-ugalan 2.penumpang masuk bus langsung hilang 3.penumpang naik bis di pinggir jalan bukan di terminal 4.banyak iklan,1,0,NaN,2021-01-31 17:09:04,NaN,NaN,NaN,2021-01
...,...,...,...,...,...,...,...,...,...,...,...,...
19477,e63ec1ff-b277-4fcf-b6c1-18096554f13f,Fikri Eka Wicaksono,https://play-lh.googleusercontent.com/a/ACg8ocJUdy43dJ22Q2vIOgQmYzwCpXhICsgYlwHtvEqwVGZRUBSHcQ=mo,tolong maleo kasih fitur untuk mabar pake mod deh maleo plisss,5,0,4.4.1,2025-11-27 16:34:15,NaN,NaN,4.4.1,2025-11
19478,8092e3ca-be43-4979-8e7e-5e5ec6587dad,Dian Zainul haq,https://play-lh.googleusercontent.com/a/ACg8ocKJczHEV4PRFpH-BkFGh_4UtairgrT3NsLITb1RXJ46-m7OAg=mo,keren banget tapi tidak ada kota jepara semoga ke depan nya ada,5,0,NaN,2025-11-03 13:06:37,NaN,NaN,NaN,2025-11
19479,f00db14e-4c59-4fee-81f9-9cb6f5b62f91,Ipunkk Whiskeyy,https://play-lh.googleusercontent.com/a-/ALV-UjWrqK3UsYvGQNoP4_cydBbgQqSZJDGFYUizNZ3BY1cCl12hGY58,banyakin kendaraan motor dong,5,0,4.4.1,2025-11-06 06:09:55,NaN,NaN,4.4.1,2025-11
19480,81d2b6b6-e1fe-4e37-b357-cf2187cadefc,Rio Reifan,https://play-lh.googleusercontent.com/a/ACg8ocIhqlRyMwUZNxKBZd7B4ZbjlWn8JNu1VSDUYqlzc84DxD_2YQ=mo,"saya mau nyetel music di go tube dan main bussid tapi malah selalu gabisa, sekarang gabisa play music dari luar pasti langsung otomatis mulai ulang apk bussidnya padahal dulu bisa emang aneh ini game lama lama. tolong jangan seperti itu juga lah saya susah mau menikmati kalau begitu caranya",2,3,4.4.1,2025-11-11 13:59:13,NaN,NaN,4.4.1,2025-11
19481,699cafdb-ebb2-4d8f-ad06-6eaefcf50c25,Johannes Roy,https://play-lh.googleusercontent.com/a/ACg8ocI1p_uNnWI8IpT-JyPxfaTEQ0xwGHC-s46LiT5kRQIGKlSkRw=mo,"bis nya kurang lengkap , voyager tidak ada dan masih banyak bis model yang lainnya tidak ada ,pilihan bis kurang puas dari 2021 hanya itu itu hanya bis tidak ada tambahan ,iklan nya terlalu lama,ambil penumpang dijalan sdah tidak ada lagi ,dan bis bis yg ada dijalanan dari pulau sumatra ,jawa ,kalimantan ,sulwesi semuanya sama(kurang puas), grafik sudah mantap dari genangan air ok ,bayangan juga mantap.. l",2,0,4.4.1,2025-11-27 14:37:59,NaN,NaN,4.4.1,2025-11

In [ ]:
import pandas as pd

# ==============================
# BACA DATA SCRAPING
# ==============================
df = pd.read_csv('/content/sample_ulasan_20persen_perbulan.csv')

# Pastikan tanggal dibaca dengan benar
df['at'] = pd.to_datetime(df['at'])

# ==============================
# BUAT KOLOM YEAR-MONTH (YYYY-MM)
# ==============================
df['year_month'] = df['at'].dt.to_period('M').astype(str)

# ==============================
# HITUNG JUMLAH ULASAN PER BULAN
# ==============================
monthly_count = df.groupby('year_month').size().reset_index(name='jumlah_ulasan')

# ==============================
# SIMPAN HASIL
# ==============================
monthly_count.to_csv('jumlah_ulasan_perbulan_2021_2025.csv', index=False, encoding='utf-8-sig')

print("📊 Rekap jumlah ulasan per bulan telah disimpan ke:")
print("➡️  jumlah_ulasan_perbulan_2021_2025.csv")

# Tampilkan 20 baris pertama
monthly_count.head(60)

📊 Rekap jumlah ulasan per bulan telah disimpan ke:
➡️  jumlah_ulasan_perbulan_2021_2025.csv

   year_month  jumlah_ulasan
0     2021-01            963
1     2021-02            600
2     2021-03            606
3     2021-04            508
4     2021-05            426
5     2021-06            833
6     2021-07            643
7     2021-08            457
8     2021-09            364
9     2021-10            362
10    2021-11            333
11    2021-12            426
12    2022-01            427
13    2022-02            284
14    2022-03            283
15    2022-04            366
16    2022-05            323
17    2022-06            376
18    2022-07            373
19    2022-08            685
20    2022-09            320
21    2022-10            255
22    2022-11            198
23    2022-12            278
24    2023-01            216
25    2023-02            172
26    2023-03            227
27    2023-04            204
28    2023-05            202
29    2023-06            188
30    2023-07            202
31    2023-08            126
32    2023-09            130
33    2023-10           1189
34    2023-11            436
35    2023-12            391
36    2024-01            355
37    2024-02            261
38    2024-03            308
39    2024-04            221
40    2024-05            213
41    2024-06            266
42    2024-07            223
43    2024-08            259
44    2024-09            209
45    2024-10            183
46    2024-11            177
47    2024-12            286
48    2025-01            229
49    2025-02            154
50    2025-03            228
51    2025-04            181
52    2025-05            228
53    2025-06            193
54    2025-07            247
55    2025-08            164
56    2025-09            161
57    2025-10            177
58    2025-11            187