# 1. Data

# Import Library

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv('/content/sample_ulasan_20persen_perbulan.csv')

# Cek informasi kolom dan tipe data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19482 entries, 0 to 19481
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              19482 non-null  object
 1   userName              19482 non-null  object
 2   userImage             19482 non-null  object
 3   content               19482 non-null  object
 4   score                 19482 non-null  int64
 5   thumbsUpCount         19482 non-null  int64
 6   reviewCreatedVersion  10698 non-null  object
 7   at                    19482 non-null  object
 8   replyContent          0 non-null      float64
 9   repliedAt             0 non-null      float64
 10  appVersion            10698 non-null  object
 11  year_month            19482 non-null  object
dtypes: float64(2), int64(2), object(8)
memory usage: 1.8+ MB

In [ ]:
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,year_month
0,dd3a3573-c2a3-4ffe-84e7-8fa9e003f745,M.Rizky Aziz,https://play-lh.googleusercontent.com/a-/ALV-U...,tolong adakan main bareng pake mod,4,0,3.4.3,2021-01-03 09:23:09,NaN,NaN,3.4.3,2021-01
1,0a4e2124-cb99-4615-a311-9c0ca649952a,Risfan Sya'bana (PanggilAkuSya'ban),https://play-lh.googleusercontent.com/a-/ALV-U...,"bagus sih....... tapi sedikit masukan ya, tolo...",5,0,NaN,2021-01-06 06:02:56,NaN,NaN,NaN,2021-01
2,2a36e8a0-9311-4049-9feb-348db14b48d2,Vickar Renaldy,https://play-lh.googleusercontent.com/a/ACg8oc...,game nya bagus tapi masih ada yang kuran misal...,5,0,NaN,2021-01-25 11:05:24,NaN,NaN,NaN,2021-01
3,56d2a53c-0968-4313-b34e-6751a78c8dd3,DAVIS Saja,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong maelo di perbanyak lagi rute nya,5,0,NaN,2021-01-23 15:23:07,NaN,NaN,NaN,2021-01
4,1d1c8c09-a758-4eff-bbc7-3cf29ad23c79,Zwarxy XR,https://play-lh.googleusercontent.com/a-/ALV-U...,game busid masih banyak kekurangannya : 1.mobi...,1,0,NaN,2021-01-31 17:09:04,NaN,NaN,NaN,2021-01
...,...,...,...,...,...,...,...,...,...,...,...,...
19477,e63ec1ff-b277-4fcf-b6c1-18096554f13f,Fikri Eka Wicaksono,https://play-lh.googleusercontent.com/a/ACg8oc...,tolong maleo kasih fitur untuk mabar pake mod ...,5,0,4.4.1,2025-11-27 16:34:15,NaN,NaN,4.4.1,2025-11
19478,8092e3ca-be43-4979-8e7e-5e5ec6587dad,Dian Zainul haq,https://play-lh.googleusercontent.com/a/ACg8oc...,keren banget tapi tidak ada kota jepara semoga...,5,0,NaN,2025-11-03 13:06:37,NaN,NaN,NaN,2025-11
19479,f00db14e-4c59-4fee-81f9-9cb6f5b62f91,Ipunkk Whiskeyy,https://play-lh.googleusercontent.com/a-/ALV-U...,banyakin kendaraan motor dong,5,0,4.4.1,2025-11-06 06:09:55,NaN,NaN,4.4.1,2025-11
19480,81d2b6b6-e1fe-4e37-b357-cf2187cadefc,Rio Reifan,https://play-lh.googleusercontent.com/a/ACg8oc...,saya mau nyetel music di go tube dan main buss...,2,3,4.4.1,2025-11-11 13:59:13,NaN,NaN,4.4.1,2025-11
19481,699cafdb-ebb2-4d8f-ad06-6eaefcf50c25,Johannes Roy,https://play-lh.googleusercontent.com/a/ACg8oc...,"bis nya kurang lengkap , voyager tidak ada dan...",2,0,4.4.1,2025-11-27 14:37:59,NaN,NaN,4.4.1,2025-11

In [ ]:
# 3 Pilih kolom yang dibutuhkan
df = df[['at', 'content']]
df

                        at                                            content
0      2021-01-03 09:23:09                 tolong adakan main bareng pake mod
1      2021-01-06 06:02:56  bagus sih....... tapi sedikit masukan ya, tolo...
2      2021-01-25 11:05:24  game nya bagus tapi masih ada yang kuran misal...
3      2021-01-23 15:23:07            tolong maelo di perbanyak lagi rute nya
4      2021-01-31 17:09:04  game busid masih banyak kekurangannya : 1.mobi...
...                    ...                                                ...
19477  2025-11-27 16:34:15  tolong maleo kasih fitur untuk mabar pake mod ...
19478  2025-11-03 13:06:37  keren banget tapi tidak ada kota jepara semoga...
19479  2025-11-06 06:09:55                      banyakin kendaraan motor dong
19480  2025-11-11 13:59:13  saya mau nyetel music di go tube dan main buss...
19481  2025-11-27 14:37:59  bis nya kurang lengkap , voyager tidak ada dan...

[19482 rows x 2 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19482 entries, 0 to 19481
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   at       19482 non-null  object
 1   content  19482 non-null  object
dtypes: object(2)
memory usage: 304.5+ KB

In [ ]:
#urutkan berdasarkan tanggal
df = df.sort_values(by='at')
df

                        at                                            content
169    2021-01-01 00:18:10  gem ya, bisapake mod truck new bekaje biar tam...
468    2021-01-01 00:19:07  mohon bussid tolong kalo narik kita dari garas...
170    2021-01-01 00:37:58  game nya udah bagu ,min tolong turunin dong mb...
299    2021-01-01 03:22:15  bang aku minta tolong kalo update ( penumpangn...
843    2021-01-01 03:32:00       semoga aupdet terbaru.. masuk kota medan....
...                    ...                                                ...
19463  2025-11-27 04:01:31  saya kasih bintang 2, karna iklan nya gak ngot...
19318  2025-11-27 04:54:37  woi ku gak bisa pasang mod mobil pls lah pls l...
19349  2025-11-27 07:44:22  padahal seru..tapi kenapa ya mentok mulu di je...
19481  2025-11-27 14:37:59  bis nya kurang lengkap , voyager tidak ada dan...
19477  2025-11-27 16:34:15  tolong maleo kasih fitur untuk mabar pake mod ...

[19482 rows x 2 columns]

# Cleansing

In [ ]:
# cek nilai yang hilang (missing values)
print(df.isnull().sum())

at         0
content    0
dtype: int64

In [ ]:
# menghapus baris dengan nilai yang hilang
df.dropna(inplace=True)

In [ ]:
# cek jumlah duplikat di kolom 'content'
duplicates_count = df['content'].duplicated().sum()
print(f"Jumlah duplikat di kolom 'content': {duplicates_count}")

# cek baris yang merupakan duplikat
duplicate_rows = df[df['content'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat:")
duplicate_rows

Jumlah duplikat di kolom 'content': 203

Baris yang merupakan duplikat:

                        at                   content
462    2021-01-01 10:02:35      terlalu banyak iklan
607    2021-01-02 08:40:30     tambahin kota bandung
296    2021-01-10 06:38:08             om telolet om
510    2021-01-11 04:20:46         game banyak iklan
334    2021-01-18 09:48:40  iklan nya terlalu banyak
...                    ...                       ...
19393  2025-11-05 23:54:23      terlalu banyak iklan
19343  2025-11-07 08:51:03      terlalu banyak iklan
19357  2025-11-09 06:50:34              banyak iklan
19412  2025-11-19 11:22:14              banyak iklan
19300  2025-11-24 23:50:08              banyak iklan

[251 rows x 2 columns]

In [ ]:
df.drop_duplicates(subset=['content'], inplace=True)

# cek jumlah duplikat di kolom 'content' setelah penghapusan
duplicates_count_after = df['content'].duplicated().sum()
print(f"\nJumlah duplikat di kolom 'isi_aduan' setelah penghapusan: {duplicates_count_after}")

# cek baris yang merupakan duplikat setelah penghapusan (seharusnya 0)
duplicate_rows_after = df[df['content'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat setelah penghapusan:")
duplicate_rows_after

Jumlah duplikat di kolom 'isi_aduan' setelah penghapusan: 0

Baris yang merupakan duplikat setelah penghapusan:

Empty DataFrame
Columns: [at, content]
Index: []

In [ ]:
print("Jumlah baris dan kolom:", df.shape)

Jumlah baris dan kolom: (19279, 2)

In [ ]:
# mencari semua spasi berlebih (termasuk tab, newline, atau banyak spasi berturut-turut) dan menggantinya dengan satu spasi saja.
df['content'] = df['content'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19279 entries, 169 to 19477
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   at       19279 non-null  object
 1   content  19279 non-null  object
dtypes: object(2)
memory usage: 451.9+ KB

In [ ]:
import re
import string
import nltk

In [ ]:
# Fungsi untuk menghapus URL
def remove_URL(tweet):
    if tweet is not None and isinstance(tweet, str):
        url = re.compile(r'https?://\S+|www\.\S+')
        return url.sub(r'', tweet)
    else:
        return tweet

# Fungsi untuk menghapus HTML
def remove_html(tweet):
    if tweet is not None and isinstance(tweet, str):
        html = re.compile(r'<.*?>')
        return html.sub(r'', tweet)
    else:
        return tweet

# Fungsi untuk menghapus emoji
def remove_emoji(tweet):
    if tweet is not None and isinstance(tweet, str):
        emoji_pattern = re.compile("["
            u"\U0001F600-\U0001F64F"  # emoticons
            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
            u"\U0001F680-\U0001F6FF"  # transport & map symbols
            u"\U0001F700-\U0001F77F"  # alchemical symbols
            u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
            u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
            u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
            u"\U0001FA00-\U0001FA6F"  # Chess Symbols
            u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
            u"\U00002702-\U000027B0"  # Additional emoticons
            u"\U0001F1E0-\U0001F1FF"  # flags
        "]+", flags=re.UNICODE)
        return emoji_pattern.sub(r'', tweet)
    else:
        return tweet

# Fungsi untuk menghapus simbol
def remove_symbols(tweet):
    if tweet is not None and isinstance(tweet, str):
        tweet = re.sub(r'[^a-zA-Z0-9\s]', '', tweet)  # Menghapus semua simbol
    return tweet

# Fungsi untuk menghapus angka
def remove_numbers(tweet):
    if tweet is not None and isinstance(tweet, str):
        tweet = re.sub(r'\d+', '', tweet)  # Menghapus semua angka
    return tweet

# Fungsi untuk menghapus username (mention)
def remove_username(text):
    import re
    return re.sub(r'@\S+', '', text)


# Terapkan secara bertahap ke 'clean_content'
df['clean_content'] = df['content'].apply(lambda x: remove_URL(x))
df['clean_content'] = df['clean_content'].apply(lambda x: remove_html(x))
df['clean_content'] = df['clean_content'].apply(lambda x: remove_emoji(x))
df['clean_content'] = df['clean_content'].apply(lambda x: remove_symbols(x))
df['clean_content'] = df['clean_content'].apply(lambda x: remove_numbers(x))
df['clean_content'] = df['clean_content'].apply(lambda x: remove_username(x))

# Tampilkan hasil
df[['content', 'clean_content']].head(5)

,content,clean_content
169,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...
468,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...
170,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...
299,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...
843,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan

In [ ]:
df

,at,content,clean_content
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan
...,...,...,...
19463,2025-11-27 04:01:31,"saya kasih bintang 2, karna iklan nya gak ngot...",saya kasih bintang karna iklan nya gak ngotak...
19318,2025-11-27 04:54:37,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...
19349,2025-11-27 07:44:22,padahal seru..tapi kenapa ya mentok mulu di je...,padahal serutapi kenapa ya mentok mulu di jeda...
19481,2025-11-27 14:37:59,"bis nya kurang lengkap , voyager tidak ada dan...",bis nya kurang lengkap voyager tidak ada dan ...
19477,2025-11-27 16:34:15,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...

In [ ]:
print("Jumlah baris dan kolom:", df.shape)

Jumlah baris dan kolom: (19279, 3)

# 2. Prapemrosesan Data

# Case Folding

In [ ]:
# Fungsi untuk mengubah huruf menjadi huruf kecil (lowercase)
def case_folding(text):
    if isinstance(text, str):
        lower_case_text = text.lower()
        return lower_case_text
    else:
        return text

# Terapkan fungsi case folding ke kolom 'cleansing'
df['case_folding'] = df['clean_content'].apply(case_folding)

# Tampilkan 5 data teratas
df.head(11829)

,at,content,clean_content,case_folding
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan
...,...,...,...,...
11915,2023-07-02 02:20:26,game ini pengen di update bus yang arjuna xhd ...,game ini pengen di update bus yang arjuna xhd ...,game ini pengen di update bus yang arjuna xhd ...
11941,2023-07-02 03:33:22,feledopel tolong tambah map lombok sebelah den...,feledopel tolong tambah map lombok sebelah den...,feledopel tolong tambah map lombok sebelah den...
12044,2023-07-02 07:37:46,sudah bagus tetapi saat memasang mod agak susah,sudah bagus tetapi saat memasang mod agak susah,sudah bagus tetapi saat memasang mod agak susah
12006,2023-07-02 12:47:20,kenapa pas in game banyak iklan jdi mls maen t...,kenapa pas in game banyak iklan jdi mls maen t...,kenapa pas in game banyak iklan jdi mls maen t...
12025,2023-07-02 16:45:07,permainan nyh sangat bagus tapi gak ada motor ...,permainan nyh sangat bagus tapi gak ada motor ...,permainan nyh sangat bagus tapi gak ada motor ...

In [ ]:
# Cek jumlah duplikat di kolom 'case_folding'
duplicates_count_case_folding = df['case_folding'].duplicated().sum()
print(f"Jumlah duplikat di kolom 'case_folding': {duplicates_count_case_folding}")

# Cek baris yang merupakan duplikat di kolom 'case_folding'
duplicate_rows_case_folding = df[df['case_folding'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat di kolom 'case_folding':")
duplicate_rows_case_folding[['at', 'content', 'clean_content', 'case_folding']]

Jumlah duplikat di kolom 'case_folding': 25

Baris yang merupakan duplikat di kolom 'case_folding':

,at,content,clean_content,case_folding
462,2021-01-01 10:02:35,terlalu banyak iklan,terlalu banyak iklan,terlalu banyak iklan
296,2021-01-10 06:38:08,om telolet om,om telolet om,om telolet om
913,2021-01-22 22:47:30,kebanyakan iklan,kebanyakan iklan,kebanyakan iklan
1187,2021-02-25 07:44:46,banyak iklan,banyak iklan,banyak iklan
1305,2021-02-25 19:26:44,tambah kota lagi dong..😀😀🤭🤭,tambah kota lagi dong,tambah kota lagi dong
1420,2021-02-27 05:31:08,banyak iklan nya,banyak iklan nya,banyak iklan nya
1824,2021-03-13 05:46:24,tambahin kota bandung dong👍,tambahin kota bandung dong,tambahin kota bandung dong
2600,2021-04-07 02:18:30,kenapa gak bisa pasang mod????????????????,kenapa gak bisa pasang mod,kenapa gak bisa pasang mod
2199,2021-04-18 02:41:33,cara masang mod gimana,cara masang mod gimana,cara masang mod gimana
2382,2021-04-21 04:32:11,mod bagus,mod bagus,mod bagus
2270,2021-04-24 02:29:52,gak bisa pasang. mod,gak bisa pasang mod,gak bisa pasang mod
2799,2021-05-18 07:07:26,kok ga bisa pasang mod ya?,kok ga bisa pasang mod ya,kok ga bisa pasang mod ya
3116,2021-06-18 13:17:05,kebanyakan iklan😤,kebanyakan iklan,kebanyakan iklan
3254,2021-06-20 15:41:27,kebanyakan iklannn,kebanyakan iklannn,kebanyakan iklannn
3350,2021-06-20 16:07:54,om telolet om...,om telolet om,om telolet om
4003,2021-07-10 04:51:29,banyak iklan nya!!!!!!!,banyak iklan nya,banyak iklan nya
6092,2021-11-19 10:42:52,kebanyakan iklan.!,kebanyakan iklan,kebanyakan iklan
6153,2021-12-06 08:11:54,gak bisa pasang mod,gak bisa pasang mod,gak bisa pasang mod
6437,2021-12-22 16:30:32,kebanyakan iklan 😡,kebanyakan iklan,kebanyakan iklan
6649,2022-01-03 12:55:14,tambahin kota bandung dong,tambahin kota bandung dong,tambahin kota bandung dong
6736,2022-01-11 14:11:56,ga bisa ganti livery....,ga bisa ganti livery,ga bisa ganti livery
6908,2022-01-14 07:47:48,banyak iklannya😣,banyak iklannya,banyak iklannya
7078,2022-02-01 21:37:22,mod!!!!!!!!!!!¡!!!!!!!!!!!!!!!!!!!!!¡!!!!!!¡¡!...,mod bagus,mod bagus
8104,2022-05-03 09:59:30,kenapa gak bisa pasang mod,kenapa gak bisa pasang mod,kenapa gak bisa pasang mod
8129,2022-05-18 22:54:46,tambah kota lagi dong,tambah kota lagi dong,tambah kota lagi dong
8072,2022-05-23 08:29:18,terlalu banyak iklan....,terlalu banyak iklan,terlalu banyak iklan
7994,2022-05-25 18:40:26,banyak iklan..,banyak iklan,banyak iklan
8796,2022-07-07 04:20:10,cara masang mod gimana..?????,cara masang mod gimana,cara masang mod gimana
9434,2022-08-09 07:10:01,banyak iklannya,banyak iklannya,banyak iklannya
9224,2022-08-14 15:14:01,kebanyakan iklan!!,kebanyakan iklan,kebanyakan iklan
11245,2023-03-09 13:32:37,kebanyakan iklan 👎,kebanyakan iklan,kebanyakan iklan
11807,2023-06-22 07:40:33,terlalu banyak iklan...,terlalu banyak iklan,terlalu banyak iklan
11957,2023-07-30 09:21:29,kebanyakan iklan !,kebanyakan iklan,kebanyakan iklan
14207,2023-12-27 06:14:58,ga bisa ganti livery,ga bisa ganti livery,ga bisa ganti livery
13997,2023-12-31 06:27:30,kok ga bisa pasang mod ya,kok ga bisa pasang mod ya,kok ga bisa pasang mod ya
15094,2024-03-20 09:23:10,kebanyakan iklan nya,kebanyakan iklan nya,kebanyakan iklan nya
16803,2024-10-12 08:45:27,game iklan,game iklan,game iklan
16947,2024-11-22 09:21:12,kebanyakan iklannn.,kebanyakan iklannn,kebanyakan iklannn
17848,2025-03-25 12:27:34,banyak iklan nya.,banyak iklan nya,banyak iklan nya
17964,2025-04-22 22:37:15,kebanyakan iklan??,kebanyakan iklan,kebanyakan iklan
18322,2025-05-01 15:34:17,banyak iklan.,banyak iklan,banyak iklan
19123,2025-10-21 15:15:09,kebanyakan iklan nya...,kebanyakan iklan nya,kebanyakan iklan nya
19401,2025-11-11 11:02:15,game iklan.,game iklan,game iklan

In [ ]:
df.drop_duplicates(subset=['case_folding'], inplace=True)

# Cek jumlah duplikat di kolom 'case_folding' setelah penghapusan
duplicates_count_after_case_folding = df['case_folding'].duplicated().sum()
print(f"\nJumlah duplikat di kolom 'case_folding' setelah penghapusan: {duplicates_count_after_case_folding}")

# Cek baris yang merupakan duplikat setelah penghapusan
duplicate_rows_after_case_folding = df[df['case_folding'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat setelah penghapusan di kolom 'case_folding':")
duplicate_rows_after_case_folding[['at', 'content', 'clean_content', 'case_folding']]
print("Jumlah baris dan kolom:", df.shape)

Jumlah duplikat di kolom 'case_folding' setelah penghapusan: 0

Baris yang merupakan duplikat setelah penghapusan di kolom 'case_folding':
Jumlah baris dan kolom: (19254, 4)

In [ ]:
df

,at,content,clean_content,case_folding
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan
...,...,...,...,...
19463,2025-11-27 04:01:31,"saya kasih bintang 2, karna iklan nya gak ngot...",saya kasih bintang karna iklan nya gak ngotak...,saya kasih bintang karna iklan nya gak ngotak...
19318,2025-11-27 04:54:37,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...
19349,2025-11-27 07:44:22,padahal seru..tapi kenapa ya mentok mulu di je...,padahal serutapi kenapa ya mentok mulu di jeda...,padahal serutapi kenapa ya mentok mulu di jeda...
19481,2025-11-27 14:37:59,"bis nya kurang lengkap , voyager tidak ada dan...",bis nya kurang lengkap voyager tidak ada dan ...,bis nya kurang lengkap voyager tidak ada dan ...
19477,2025-11-27 16:34:15,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...

# Tokenize

In [ ]:
def tokenize(text):
    tokens = text.split()
    return tokens

df['tokenize'] = df['case_folding'].apply(tokenize)
df.head(5)

,at,content,clean_content,case_folding,tokenize
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b..."
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar..."
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ..."
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum..."
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]"

In [ ]:
# Cek jumlah duplikat di kolom 'tokenize'
duplicates_count_tokenize = df['tokenize'].duplicated().sum()
print(f"Jumlah duplikat di kolom 'tokenize': {duplicates_count_tokenize}")

# Cek baris yang merupakan duplikat di kolom 'tokenize'
duplicate_rows_tokenize = df[df['tokenize'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat di kolom 'tokenize':")
duplicate_rows_tokenize[['at', 'content', 'clean_content', 'case_folding', 'tokenize']]

Jumlah duplikat di kolom 'tokenize': 5

Baris yang merupakan duplikat di kolom 'tokenize':

,at,content,clean_content,case_folding,tokenize
462,2021-01-01 10:02:35,terlalu banyak iklan,terlalu banyak iklan,terlalu banyak iklan,"[terlalu, banyak, iklan]"
913,2021-01-22 22:47:30,kebanyakan iklan,kebanyakan iklan,kebanyakan iklan,"[kebanyakan, iklan]"
1076,2021-02-09 01:10:32,mod,mod,mod,[mod]
1420,2021-02-27 05:31:08,banyak iklan nya,banyak iklan nya,banyak iklan nya,"[banyak, iklan, nya]"
6437,2021-12-22 16:30:32,kebanyakan iklan 😡,kebanyakan iklan,kebanyakan iklan,"[kebanyakan, iklan]"
8091,2022-05-25 07:22:17,iklan,iklan,iklan,[iklan]
10807,2023-01-25 08:40:50,terlalu banyak iklan 🗿,terlalu banyak iklan,terlalu banyak iklan,"[terlalu, banyak, iklan]"
11308,2023-04-12 03:32:53,mod 🚚,mod,mod,[mod]
15795,2024-06-26 03:40:58,😂😂😂😂 banyak iklan nya,banyak iklan nya,banyak iklan nya,"[banyak, iklan, nya]"
18801,2025-08-23 12:20:55,50% iklan,iklan,iklan,[iklan]

In [ ]:
df.drop_duplicates(subset=['tokenize'], inplace=True)

# Cek jumlah duplikat di kolom 'tokenize' setelah penghapusan
duplicates_count_after_tokenize = df['tokenize'].duplicated().sum()
print(f"\nJumlah duplikat di kolom 'tokenize' setelah penghapusan: {duplicates_count_after_tokenize}")

# Cek baris yang merupakan duplikat setelah penghapusan
duplicate_rows_after_tokenize = df[df['tokenize'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat setelah penghapusan di kolom 'tokenize':")
duplicate_rows_after_tokenize[['content', 'clean_content', 'case_folding', 'tokenize']]
print("Jumlah baris dan kolom:", df.shape)

Jumlah duplikat di kolom 'tokenize' setelah penghapusan: 0

Baris yang merupakan duplikat setelah penghapusan di kolom 'tokenize':
Jumlah baris dan kolom: (19249, 5)

In [ ]:
df

,at,content,clean_content,case_folding,tokenize
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b..."
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar..."
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ..."
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum..."
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]"
...,...,...,...,...,...
19463,2025-11-27 04:01:31,"saya kasih bintang 2, karna iklan nya gak ngot...",saya kasih bintang karna iklan nya gak ngotak...,saya kasih bintang karna iklan nya gak ngotak...,"[saya, kasih, bintang, karna, iklan, nya, gak,..."
19318,2025-11-27 04:54:37,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...,"[woi, ku, gak, bisa, pasang, mod, mobil, pls, ..."
19349,2025-11-27 07:44:22,padahal seru..tapi kenapa ya mentok mulu di je...,padahal serutapi kenapa ya mentok mulu di jeda...,padahal serutapi kenapa ya mentok mulu di jeda...,"[padahal, serutapi, kenapa, ya, mentok, mulu, ..."
19481,2025-11-27 14:37:59,"bis nya kurang lengkap , voyager tidak ada dan...",bis nya kurang lengkap voyager tidak ada dan ...,bis nya kurang lengkap voyager tidak ada dan ...,"[bis, nya, kurang, lengkap, voyager, tidak, ad..."
19477,2025-11-27 16:34:15,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...,"[tolong, maleo, kasih, fitur, untuk, mabar, pa..."

# Removing Stopwords

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)

In [ ]:
from nltk.corpus import stopwords
import nltk

# Download stopword jika belum ada
nltk.download('stopwords')

# Stopword NLTK Bahasa Indonesia
stop_words_nltk = set(stopwords.words('indonesian'))

# Stopword Manual (Play Store)
stop_words_manual = set([
    'ya', 'iya', 'yah', 'hehe', 'wkwk', 'lol',
    'nya', 'dong', 'deh', 'sih',
    'kalo', 'kalau', 'aja', 'ajaa', 'kalo'
    'aplikasi', 'game', 'gem',
    'playstore', 'nya', 'kalo', 'yang','dan','di','ke','dari','ini','itu','untuk','dengan'
])

# Gabungan stopword
stopwords_final = stop_words_nltk.union(stop_words_manual)

# Fungsi hapus stopword
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stopwords_final]

# Terapkan ke DataFrame
df['stopword removal'] = df['tokenize'].apply(remove_stopwords)
df

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

,at,content,clean_content,case_folding,tokenize,stopword removal
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b...","[bisapake, mod, truck, new, bekaje, biar, keten]"
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar...","[mohon, bussid, tolong, narik, garasi, termina..."
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ...","[udah, bagu, min, tolong, turunin, mb, buad, m..."
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum...","[bang, tolong, update, penumpangnya, terminal,..."
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]","[semoga, aupdet, terbaru, masuk, kota, medan]"
...,...,...,...,...,...,...
19463,2025-11-27 04:01:31,"saya kasih bintang 2, karna iklan nya gak ngot...",saya kasih bintang karna iklan nya gak ngotak...,saya kasih bintang karna iklan nya gak ngotak...,"[saya, kasih, bintang, karna, iklan, nya, gak,...","[kasih, bintang, karna, iklan, gak, ngotak, de..."
19318,2025-11-27 04:54:37,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...,"[woi, ku, gak, bisa, pasang, mod, mobil, pls, ...","[woi, ku, gak, pasang, mod, mobil, pls, pls, b..."
19349,2025-11-27 07:44:22,padahal seru..tapi kenapa ya mentok mulu di je...,padahal serutapi kenapa ya mentok mulu di jeda...,padahal serutapi kenapa ya mentok mulu di jeda...,"[padahal, serutapi, kenapa, ya, mentok, mulu, ...","[serutapi, mentok, mulu, jeda, iklan]"
19481,2025-11-27 14:37:59,"bis nya kurang lengkap , voyager tidak ada dan...",bis nya kurang lengkap voyager tidak ada dan ...,bis nya kurang lengkap voyager tidak ada dan ...,"[bis, nya, kurang, lengkap, voyager, tidak, ad...","[bis, lengkap, voyager, bis, model, pilihan, b..."
19477,2025-11-27 16:34:15,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...,"[tolong, maleo, kasih, fitur, untuk, mabar, pa...","[tolong, maleo, kasih, fitur, mabar, pake, mod..."

In [ ]:
df['stopword_removal_tuple'] = df['stopword removal'].apply(tuple)
duplicates_count_stopword = df['stopword_removal_tuple'].duplicated().sum()
print(f"Jumlah duplikat di kolom 'stopword removal': {duplicates_count_stopword}")

# Cek baris yang merupakan duplikat di kolom 'stopword removal'
duplicate_rows_stopword = df[df['stopword_removal_tuple'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat di kolom 'stopword removal':")
print(duplicate_rows_stopword[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal']])

Jumlah duplikat di kolom 'stopword removal': 358

Baris yang merupakan duplikat di kolom 'stopword removal':
                                          content  \
462                          terlalu banyak iklan
607                         tambahin kota bandung
371                       bagus bisa dipasang mod
318                     kapan mod bisa buat mabar
510                             game banyak iklan
...                                           ...
19125                   bagus sekali banyak iklan
19149                 bagus sih tapi banyak iklan
19402  kok setiap pasang mod mulai dari awal lagi
19474                 iklan nya sangat mengganggu
19469                        tidak bisa pakai mod

                                    clean_content  \
462                          terlalu banyak iklan
607                         tambahin kota bandung
371                       bagus bisa dipasang mod
318                     kapan mod bisa buat mabar
510                             game banyak iklan
...                                           ...
19125                   bagus sekali banyak iklan
19149                 bagus sih tapi banyak iklan
19402  kok setiap pasang mod mulai dari awal lagi
19474                 iklan nya sangat mengganggu
19469                        tidak bisa pakai mod

                                     case_folding  \
462                          terlalu banyak iklan
607                         tambahin kota bandung
371                       bagus bisa dipasang mod
318                     kapan mod bisa buat mabar
510                             game banyak iklan
...                                           ...
19125                   bagus sekali banyak iklan
19149                 bagus sih tapi banyak iklan
19402  kok setiap pasang mod mulai dari awal lagi
19474                 iklan nya sangat mengganggu
19469                        tidak bisa pakai mod

                                                tokenize  \
462                             [terlalu, banyak, iklan]
607                            [tambahin, kota, bandung]
371                         [bagus, bisa, dipasang, mod]
318                      [kapan, mod, bisa, buat, mabar]
510                                [game, banyak, iklan]
...                                                  ...
19125                     [bagus, sekali, banyak, iklan]
19149                  [bagus, sih, tapi, banyak, iklan]
19402  [kok, setiap, pasang, mod, mulai, dari, awal, ...
19474                   [iklan, nya, sangat, mengganggu]
19469                          [tidak, bisa, pakai, mod]

                stopword removal
462                      [iklan]
607    [tambahin, kota, bandung]
371       [bagus, dipasang, mod]
318                 [mod, mabar]
510                      [iklan]
...                          ...
19125             [bagus, iklan]
19149             [bagus, iklan]
19402              [pasang, mod]
19474        [iklan, mengganggu]
19469               [pakai, mod]

[490 rows x 5 columns]

In [ ]:
# Hapus duplikat di kolom 'stopword removal'
df.drop_duplicates(subset=['stopword_removal_tuple'], inplace=True)

# Cek jumlah duplikat di kolom 'stopword removal' setelah penghapusan
duplicates_count_after_stopword = df['stopword_removal_tuple'].duplicated().sum()
print(f"\nJumlah duplikat di kolom 'stopword removal' setelah penghapusan: {duplicates_count_after_stopword}")

# Cek baris yang merupakan duplikat setelah penghapusan
duplicate_rows_after_stopword = df[df['stopword_removal_tuple'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat setelah penghapusan di kolom 'stopword removal':")
print(duplicate_rows_after_stopword[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal']])

print("Jumlah baris dan kolom:", df.shape)

df.drop(columns=['stopword_removal_tuple'], inplace=True)

# Tampilkan 5 baris pertama
df.head(5)

Jumlah duplikat di kolom 'stopword removal' setelah penghapusan: 0

Baris yang merupakan duplikat setelah penghapusan di kolom 'stopword removal':
Empty DataFrame
Columns: [content, clean_content, case_folding, tokenize, stopword removal]
Index: []
Jumlah baris dan kolom: (18891, 7)

,at,content,clean_content,case_folding,tokenize,stopword removal
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b...","[bisapake, mod, truck, new, bekaje, biar, keten]"
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar...","[mohon, bussid, tolong, narik, garasi, termina..."
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ...","[udah, bagu, min, tolong, turunin, mb, buad, m..."
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum...","[bang, tolong, update, penumpangnya, terminal,..."
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]","[semoga, aupdet, terbaru, masuk, kota, medan]"

In [ ]:
!pip install Sastrawi

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.2 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_text(text):
    return [stemmer.stem(word) for word in text]

df['steming_data'] = df['stopword removal'].apply(lambda x: ' '.join(stem_text(x)))
df.head(5)

,at,content,clean_content,case_folding,tokenize,stopword removal,steming_data
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b...","[bisapake, mod, truck, new, bekaje, biar, keten]",bisapake mod truck new bekaje biar keten
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar...","[mohon, bussid, tolong, narik, garasi, termina...",mohon bussid tolong narik garasi terminaltamba...
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ...","[udah, bagu, min, tolong, turunin, mb, buad, m...",udah bagu min tolong turunin mb buad mod knalp...
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum...","[bang, tolong, update, penumpangnya, terminal,...",bang tolong update tumpang terminal rute tol t...
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]","[semoga, aupdet, terbaru, masuk, kota, medan]",moga aupdet baru masuk kota medan

In [ ]:
# cek jumlah duplikat di kolom 'steming_data'
duplicates_count_steming_data = df['steming_data'].duplicated().sum()
print(f"Jumlah duplikat di kolom 'steming_data': {duplicates_count_steming_data}")

# Cek baris yang merupakan duplikat di kolom 'steming_data'
duplicate_rows_steming_data = df[df['steming_data'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat di kolom 'steming_data':")
print(duplicate_rows_steming_data[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal', 'steming_data']])

Jumlah duplikat di kolom 'steming_data': 61

Baris yang merupakan duplikat di kolom 'steming_data':
                                            content  \
462                            terlalu banyak iklan
420     gem ini sangat bagus saya bisa memasang mod
371                         bagus bisa dipasang mod
308                             kotanya tambah lagi
765                           tambahkan kota malang
...                                             ...
18655  game nya bagus tapi tolong hilangin iklannya
19114                           banyak iklan haram🫵
19459                    sayang masih ada iklan nya
19383                      banyak iklan bikin emosi
19431         game nya bagus tapi kurangi iklan nya

                                      clean_content  \
462                            terlalu banyak iklan
420     gem ini sangat bagus saya bisa memasang mod
371                         bagus bisa dipasang mod
308                             kotanya tambah lagi
765                           tambahkan kota malang
...                                             ...
18655  game nya bagus tapi tolong hilangin iklannya
19114                            banyak iklan haram
19459                    sayang masih ada iklan nya
19383                      banyak iklan bikin emosi
19431         game nya bagus tapi kurangi iklan nya

                                       case_folding  \
462                            terlalu banyak iklan
420     gem ini sangat bagus saya bisa memasang mod
371                         bagus bisa dipasang mod
308                             kotanya tambah lagi
765                           tambahkan kota malang
...                                             ...
18655  game nya bagus tapi tolong hilangin iklannya
19114                            banyak iklan haram
19459                    sayang masih ada iklan nya
19383                      banyak iklan bikin emosi
19431         game nya bagus tapi kurangi iklan nya

                                                tokenize  \
462                             [terlalu, banyak, iklan]
420    [gem, ini, sangat, bagus, saya, bisa, memasang...
371                         [bagus, bisa, dipasang, mod]
308                              [kotanya, tambah, lagi]
765                            [tambahkan, kota, malang]
...                                                  ...
18655  [game, nya, bagus, tapi, tolong, hilangin, ikl...
19114                             [banyak, iklan, haram]
19459                   [sayang, masih, ada, iklan, nya]
19383                      [banyak, iklan, bikin, emosi]
19431      [game, nya, bagus, tapi, kurangi, iklan, nya]

                          stopword removal                 steming_data
462                                [iklan]                        iklan
420                 [bagus, memasang, mod]             bagus pasang mod
371                 [bagus, dipasang, mod]             bagus pasang mod
308                              [kotanya]                         kota
765              [tambahkan, kota, malang]           tambah kota malang
...                                    ...                          ...
18655  [bagus, tolong, hilangin, iklannya]  bagus tolong hilangin iklan
19114                       [iklan, haram]                  iklan haram
19459                      [sayang, iklan]                 sayang iklan
19383                [iklan, bikin, emosi]            iklan bikin emosi
19431              [bagus, kurangi, iklan]           bagus kurang iklan

[115 rows x 6 columns]

In [ ]:
# Hapus duplikat di kolom 'steming_data'
df.drop_duplicates(subset=['steming_data'], inplace=True)

# Cek jumlah duplikat di kolom 'steming_data' setelah penghapusan
duplicates_count_after_steming_data = df['steming_data'].duplicated().sum()
print(f"\nJumlah duplikat di kolom 'steming_data' setelah penghapusan: {duplicates_count_after_steming_data}")

# Cek baris yang merupakan duplikat setelah penghapusan
duplicate_rows_after_steming_data = df[df['steming_data'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat setelah penghapusan di kolom 'steming_data':")
print(duplicate_rows_after_steming_data[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal', 'steming_data']])

print("Jumlah baris dan kolom:", df.shape)

# Tampilkan 5 baris pertama
df.head(5)

Jumlah duplikat di kolom 'steming_data' setelah penghapusan: 0

Baris yang merupakan duplikat setelah penghapusan di kolom 'steming_data':
Empty DataFrame
Columns: [content, clean_content, case_folding, tokenize, stopword removal, steming_data]
Index: []
Jumlah baris dan kolom: (18830, 7)

,at,content,clean_content,case_folding,tokenize,stopword removal,steming_data
169,2021-01-01 00:18:10,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b...","[bisapake, mod, truck, new, bekaje, biar, keten]",bisapake mod truck new bekaje biar keten
468,2021-01-01 00:19:07,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar...","[mohon, bussid, tolong, narik, garasi, termina...",mohon bussid tolong narik garasi terminaltamba...
170,2021-01-01 00:37:58,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ...","[udah, bagu, min, tolong, turunin, mb, buad, m...",udah bagu min tolong turunin mb buad mod knalp...
299,2021-01-01 03:22:15,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum...","[bang, tolong, update, penumpangnya, terminal,...",bang tolong update tumpang terminal rute tol t...
843,2021-01-01 03:32:00,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]","[semoga, aupdet, terbaru, masuk, kota, medan]",moga aupdet baru masuk kota medan

In [ ]:
# Hapus baris yang memiliki nilai kosong (NaN, None, atau string kosong) di kolom 'steming_data'
df.dropna(subset=['steming_data'], inplace=True)
df = df[df['steming_data'] != '']

In [ ]:
# gabungkan token hasil stemming
df['steming_data'] = df['steming_data'].apply(lambda x: ' '.join(x))

In [ ]:
# gabungkan token hasil stemming
df['steming_data'] = df['steming_data'].apply(lambda x: ' '.join(x))

In [ ]:
df['steming_data'].to_csv('stemming_data.csv', index=False)

# Normalisasi

In [ ]:
import pandas as pd

# Fungsi penggantian kata tidak baku
def replace_taboo_words(text, kamus_tidak_baku):
    if isinstance(text, str):
        words = text.split()
        replaced_words = []
        kalimat_baku = []
        kata_diganti = []
        kata_tidak_baku_hash = []

        for word in words:
            if word in kamus_tidak_baku:
                baku_word = kamus_tidak_baku[word]
                if isinstance(baku_word, str) and all(char.isalpha() or char.isspace() for char in baku_word):
                    replaced_words.append(baku_word)
                    kalimat_baku.append(baku_word)
                    kata_diganti.append(word)
                    kata_tidak_baku_hash.append(hash(word))
                else:
                    replaced_words.append(word)
            else:
                replaced_words.append(word)
        replaced_text = ' '.join(replaced_words)
    else:
        replaced_text = ''
        kalimat_baku = []
        kata_diganti = []
        kata_tidak_baku_hash = []

    return replaced_text, kalimat_baku, kata_diganti, kata_tidak_baku_hash

In [ ]:
# baca dataset
data = pd.DataFrame(df[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal', 'steming_data']])
data.head(5)

,content,clean_content,case_folding,tokenize,stopword removal,steming_data
169,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b...","[bisapake, mod, truck, new, bekaje, biar, keten]",bisapake mod truck new bekaje biar keten
468,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar...","[mohon, bussid, tolong, narik, garasi, termina...",mohon bussid tolong narik garasi terminaltamba...
170,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ...","[udah, bagu, min, tolong, turunin, mb, buad, m...",udah bagu min tolong turunin mb buad mod knalp...
299,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum...","[bang, tolong, update, penumpangnya, terminal,...",bang tolong update tumpang terminal rute tol t...
843,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]","[semoga, aupdet, terbaru, masuk, kota, medan]",moga aupdet baru masuk kota medan

In [ ]:
# baca kamus kata tidak baku
kamus_data = pd.read_excel('/content/kamuskatabaku.xlsx')
kamus_tidak_baku = dict(zip(kamus_data['tidak_baku'], kamus_data['kata_baku']))

In [ ]:
# Terapkan fungsi penggantian kata tidak baku
data[['normalisasi', 'kata_baku', 'kata_Tidak_Baku', 'kata_Tidak_Baku_Hash']] = data['steming_data'].apply(lambda x: replace_taboo_words(x, kamus_tidak_baku)).apply(pd.Series)

# Buat DataFrame baru 'df' dengan kolom yang dipilih
df = pd.DataFrame(data[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal', 'steming_data', 'normalisasi']])

# Tampilkan 5 baris pertama

In [ ]:
# cek jumlah duplikat di kolom 'normalisasi'
duplicates_count_normalisasi = df['normalisasi'].duplicated().sum()
print(f"Jumlah duplikat di kolom 'normalisasi': {duplicates_count_normalisasi}")

# Cek baris yang merupakan duplikat di kolom 'normalisasi'
duplicate_rows_normalisasi = df[df['normalisasi'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat di kolom 'normalisasi':")
duplicate_rows_normalisasi[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal', 'steming_data', 'normalisasi']]

Jumlah duplikat di kolom 'normalisasi': 85

Baris yang merupakan duplikat di kolom 'normalisasi':

,content,clean_content,case_folding,tokenize,stopword removal,steming_data,normalisasi
830,kenapa game ini gk bisa mabar pakek mod?,kenapa game ini gk bisa mabar pakek mod,kenapa game ini gk bisa mabar pakek mod,"[kenapa, game, ini, gk, bisa, mabar, pakek, mod]","[gk, mabar, pakek, mod]",gk mabar pakek mod,tidak mabar pakai mod
446,bisa oleng dan bisa juga pakai mod,bisa oleng dan bisa juga pakai mod,bisa oleng dan bisa juga pakai mod,"[bisa, oleng, dan, bisa, juga, pakai, mod]","[oleng, pakai, mod]",oleng pakai mod,oleng pakai mod
779,baguss ada mod nya,baguss ada mod nya,baguss ada mod nya,"[baguss, ada, mod, nya]","[baguss, mod]",baguss mod,bagus mod
89,game ini bagus banget bisa pakai mod,game ini bagus banget bisa pakai mod,game ini bagus banget bisa pakai mod,"[game, ini, bagus, banget, bisa, pakai, mod]","[bagus, banget, pakai, mod]",bagus banget pakai mod,bagus banget pakai mod
345,tolong dong kalo mabar bisa pake mod,tolong dong kalo mabar bisa pake mod,tolong dong kalo mabar bisa pake mod,"[tolong, dong, kalo, mabar, bisa, pake, mod]","[tolong, mabar, pake, mod]",tolong mabar pake mod,tolong mabar pakai mod
...,...,...,...,...,...,...,...
19005,gak bisa mabar pake mod,gak bisa mabar pake mod,gak bisa mabar pake mod,"[gak, bisa, mabar, pake, mod]","[gak, mabar, pake, mod]",gak mabar pake mod,tidak mabar pakai mod
19047,"sekarang bnyak iklanya,",sekarang bnyak iklanya,sekarang bnyak iklanya,"[sekarang, bnyak, iklanya]","[bnyak, iklanya]",bnyak iklanya,banyak iklanya
19079,banyak bet iklan,banyak bet iklan,banyak bet iklan,"[banyak, bet, iklan]","[bet, iklan]",bet iklan,banget iklan
19265,game seru bisa pakai mod lagi,game seru bisa pakai mod lagi,game seru bisa pakai mod lagi,"[game, seru, bisa, pakai, mod, lagi]","[seru, pakai, mod]",seru pakai mod,seru pakai mod
19232,game nya seru banget apa lagi pakek mod truk,game nya seru banget apa lagi pakek mod truk,game nya seru banget apa lagi pakek mod truk,"[game, nya, seru, banget, apa, lagi, pakek, mo...","[seru, banget, pakek, mod, truk]",seru banget pakek mod truk,seru banget pakai mod truk

In [ ]:
# Hapus duplikat di kolom 'normalisasi'
df.drop_duplicates(subset=['normalisasi'], inplace=True)

# Cek jumlah duplikat di kolom 'normalisasi' setelah penghapusan
duplicates_count_after_normalisasi = df['normalisasi'].duplicated().sum()
print(f"\nJumlah duplikat di kolom 'normalisasi' setelah penghapusan: {duplicates_count_after_normalisasi}")

# Cek baris yang merupakan duplikat setelah penghapusan
duplicate_rows_after_normalisasi = df[df['normalisasi'].duplicated(keep=False)]
print("\nBaris yang merupakan duplikat setelah penghapusan di kolom 'normalisasi':")
duplicate_rows_after_normalisasi[['content', 'clean_content', 'case_folding', 'tokenize', 'stopword removal', 'steming_data', 'normalisasi']]
print("Jumlah baris dan kolom:", df.shape)

# Tampilkan 5 baris pertama

Jumlah duplikat di kolom 'normalisasi' setelah penghapusan: 0

Baris yang merupakan duplikat setelah penghapusan di kolom 'normalisasi':
Jumlah baris dan kolom: (18745, 7)

In [ ]:
df

,content,clean_content,case_folding,tokenize,stopword removal,steming_data,normalisasi
169,"gem ya, bisapake mod truck new bekaje biar tam...",gem ya bisapake mod truck new bekaje biar tamb...,gem ya bisapake mod truck new bekaje biar tamb...,"[gem, ya, bisapake, mod, truck, new, bekaje, b...","[bisapake, mod, truck, new, bekaje, biar, keten]",bisapake mod truck new bekaje biar keten,bisapake mod truck new bekaje biar keten
468,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,mohon bussid tolong kalo narik kita dari garas...,"[mohon, bussid, tolong, kalo, narik, kita, dar...","[mohon, bussid, tolong, narik, garasi, termina...",mohon bussid tolong narik garasi terminaltamba...,mohon bussid tolong menarik garasi terminaltam...
170,"game nya udah bagu ,min tolong turunin dong mb...",game nya udah bagu min tolong turunin dong mb ...,game nya udah bagu min tolong turunin dong mb ...,"[game, nya, udah, bagu, min, tolong, turunin, ...","[udah, bagu, min, tolong, turunin, mb, buad, m...",udah bagu min tolong turunin mb buad mod knalp...,sudah bagu min tolong turunin mbak buad mod kn...
299,bang aku minta tolong kalo update ( penumpangn...,bang aku minta tolong kalo update penumpangny...,bang aku minta tolong kalo update penumpangny...,"[bang, aku, minta, tolong, kalo, update, penum...","[bang, tolong, update, penumpangnya, terminal,...",bang tolong update tumpang terminal rute tol t...,abang tolong update tumpang terminal rute tol ...
843,semoga aupdet terbaru.. masuk kota medan....,semoga aupdet terbaru masuk kota medan,semoga aupdet terbaru masuk kota medan,"[semoga, aupdet, terbaru, masuk, kota, medan]","[semoga, aupdet, terbaru, masuk, kota, medan]",moga aupdet baru masuk kota medan,moga aupdet baru masuk kota medan
...,...,...,...,...,...,...,...
19463,"saya kasih bintang 2, karna iklan nya gak ngot...",saya kasih bintang karna iklan nya gak ngotak...,saya kasih bintang karna iklan nya gak ngotak...,"[saya, kasih, bintang, karna, iklan, nya, gak,...","[kasih, bintang, karna, iklan, gak, ngotak, de...",kasih bintang karna iklan gak ngotak detik ikl...,kasih bintang karena iklan tidak ngotak detik ...
19318,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...,woi ku gak bisa pasang mod mobil pls lah pls l...,"[woi, ku, gak, bisa, pasang, mod, mobil, pls, ...","[woi, ku, gak, pasang, mod, mobil, pls, pls, b...",woi ku gak pasang mod mobil pls pls bikin,woi ku tidak pasang mod mobil pls pls bikin
19349,padahal seru..tapi kenapa ya mentok mulu di je...,padahal serutapi kenapa ya mentok mulu di jeda...,padahal serutapi kenapa ya mentok mulu di jeda...,"[padahal, serutapi, kenapa, ya, mentok, mulu, ...","[serutapi, mentok, mulu, jeda, iklan]",serutapi mentok mulu jeda iklan,serutapi mentok mulu jeda iklan
19481,"bis nya kurang lengkap , voyager tidak ada dan...",bis nya kurang lengkap voyager tidak ada dan ...,bis nya kurang lengkap voyager tidak ada dan ...,"[bis, nya, kurang, lengkap, voyager, tidak, ad...","[bis, lengkap, voyager, bis, model, pilihan, b...",bis lengkap voyager bis model pilih bis puas b...,bis lengkap voyager bis model pilih bis puas b...
19477,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...,tolong maleo kasih fitur untuk mabar pake mod ...,"[tolong, maleo, kasih, fitur, untuk, mabar, pa...","[tolong, maleo, kasih, fitur, mabar, pake, mod...",tolong maleo kasih fitur mabar pake mod maleo ...,tolong maleo kasih fitur mabar pakai mod maleo...

In [ ]:
# Hapus baris yang memiliki nilai kosong (NaN, None, atau string kosong) di kolom 'normalisasi'
df.dropna(subset=['normalisasi'], inplace=True)
df = df[df['normalisasi'] != '']

In [ ]:
df['normalisasi'].to_csv('normalisasi.csv', index=False)

In [ ]:
kamus_data = pd.read_excel('/content/kamuskatabaku.xlsx')
# kolom: tidak_baku | baku

# ubah ke dictionary
kamus = dict(zip(
    kamus_data['tidak_baku'].astype(str).str.lower(),
    kamus_data['kata_baku'].astype(str).str.lower()
))

In [ ]:
manual_rules = {
 "gk": "tidak", "ga": "tidak", "ngga": "tidak", "nggak": "tidak", "tdk": "tidak",
    "tdak": "tidak", "tak": "tidak",
    "bgt": "banget", "bget": "banget", "sgt": "sangat",
    "pls": "tolong", "plis": "tolong", "pliss": "tolong","plisss": "tolong", "tlng": "tolong", "tolng": "tolong", "plissssssss": "tolong",
    "ok": "oke", "okeh": "oke",
    "pake": "pakai", "pke": "pakai",
    "bgs": "bagus", "bgus": "bagus",
    "bang": "abang", "bg": "bang",
    "gmna": "bagaimana", "gmn": "bagaimana", "god": "baik", "good": "baik", "jossss": "bagus", "josss": "bagus", "josss": "bagus", "sru": "seru", "sry": "seru", "ye": "asyik", "mantep": "mantap",
    "dmn": "di mana",
    "skr": "sekarang", "skrg": "sekarang", "skrng": "sekarang",
    "udh": "sudah", "udah": "sudah", "sdh": "sudah",
    "cpet": "cepat", "cepet": "cepat",
    "bnyk": "banyak", "byk": "banyak",
    "dpt": "dapat", "dapet": "dapat",
    "lg": "lagi", "lgi": "lagi",
    "trs": "terus", "trus": "terus",
    "moga": "semoga",
    "gamenya": "gim",
    "mantul": "mantap", "mantab": "mantap",
    "wkwk": "tertawa", "wk": "tertawa",
    "aje": "saja", "aj": "saja", "aja": "saja",
    "min": "admin",
    "gem": "gim", "game": "gim",
    "bisapake": "bisa pakai",
    "truck": "truk", "new": "baru", "bekaje": "bekasaje", "keten": "keren",
    "terminaltambahin": "terminal tambah", "lagisaya": "lagi saya", "updatenya": "memperbarui", "aupdet": "memperbarui", "apdate": "memperbarui", "apdet": "memperbarui", "updatean": "memperbarui",
    "bagu": "bagus", "turunin": "turun", "buad": "buat", "benerran": "bener", "tolongg": "tolong", "iteus": "terus", "belomabde": "belum perbarui",
    "matidh": "mati saja", "ajakgimenya": "ajak gim", "spongsornya": "sponsor", "sikitdn sngat": "sedikit banget", "bagustapi": "bagus tapi",
    "next": "lanjut", "mabar": "main bareng", "kediritulung": "kediri tolong", "agungmalangjogjatrustrenggalek": "agung malang jogja terus trenggalek",
    "tambahkan": "tambah", "menambah": "tambah", "perovinsi": "provinsi", "nabrak": "tabrak", "mubil": "mobil", "yoderek": "derek", "benr": "benar",
    "mendonloand": "unduh", "mendonlod": "unduh", "mendonload": "unduh", "download": "unduh", "downloag": "unduh", "donlod": "unduh", "hp": "ponsel", "iini": "ini", "tidah": "tidak", "you tube": "aplikasi youtube",
    "buss": "bus", "mondak mandek": "berhenti", "banyakkkkk": "banyak", "iklannn": "iklan", "skalli": "sekali", "tambhin": "tambah", "tempattempatnya": "tempat tempat",
    "developers": "pengembang", "developer": "pengembang", "developernya": "pengembang", "indonesi": "indonesia", "tementemen": "teman teman",
    "request": "rekomendasi", "anehhgua": "aneh aku", "geronjal geronjal": "tidak rata", "pool": "pul", "sukatp": "suka tapi", "nttkan": "NTT",
    "anjinmmmg": "anjing", "bang": "abang", "mintakk": "minta", "bgjangan": "abang jangan", "bagustapi": "bagus tapi", "tolongbeet": "tolong banget", "nitolong": "ini tolong",
    "kotakendaraandll": "kota kendaraan", "semarangsudah": "semarang sudah", "berlumpurterus": "lumpur terus", "airsekalian": "air sekalian", "ramaikalo": "ramai kalau",
    "jugapokok": "juga pokok", "mkasihhh": "terima kasih", "inggin": "ingin", "sihtp": "tapi", "fiturtambah": "fitur tambah", "magelangfitur": "magelang fitur",
    "kecelakaantambahin": "kecelakaan tambah", " jalanjalan": "jalan jalan", "etsitu": "itu", "sngat": "sangat", "tlong": "tolong", "overall": "keseluruhan", "selalukomen": "selalu komen",
    "bagu": "bagus", "multiplater": "multi pemain", "mengasih": "kasih", "devmaleo": "pengembang maleo", " initingkatkan": "ini tingkat", "real power of indonesia wonderful indonesia": "kekuatan sejati Indonesia yang luar biasa",
    "ngelagann": "lambat", "buriktolong": "jelek tolong", "burikkkkkkkkkkpacemana": "jelek bagaimana", "mic audio": "audio mikrofon", " bagusssss": "bagus", "iklanatau": "iklan atau",
    "seruuuuuuu": "seru", "ditambahin": "tambah", "olengvya": "oleng", "tulong": "tolong", "tanbahin": "tambah", "prmintaan": "permintaan", "rutenyasaya": "jalur saya", "nagreg": "narik",
    "bedakanterus": "bedakan terus", "trakc": "jalur", "cepatloding": "proses pemuatan dipercepat", "ketutupsoal": "tertutup", "loding": "proses pemuatan", "ketutupgak": "tertutup tidak",
    "kaliata": "terlihat", "nyatolong": "tolong", "blampungtolong": "lampung tolong", "sumateratrimakasih": "sumatera terima kasih", "ditanbah": "tambah", "jelektapi": "jelek tapi",
    "bal": "bali", "kotakotanya": "kota kota", "grapfik": "grafik", "bangettapi": "banget tapi", "bagusbisa": "bagus bisa", "kayak": "seperti", "olengbus": "oleng bus", "terhura": "terharu",
    "mengomongnya": "bicara", "offline online": "luring daring", "bohonggggg": "bohong", "pilittt": "pelit", "knalpotnya": "knalpot", "sabil": "sambil", "berharappp": "berharap",
    "tolonggggg": "tolong", "bisaaaa": "bisa", "moddd": "mod", "gituuuu": "begitu", "danfariasi": "dan fariasi", "bangtap": "abang tapi", "tolongharga": "tolong harga", "bangetttttap": "banget tapi",
    "liveryi": "livery", "gameplay": "gim", "kotaa": "kota", "gameny": "gim", "dev": "pengembang", "hancurr": "hancur", "tapiseharusnya": "tapi seharusnya", "jalankaca": "jalan kaca",
    "seloka": "selokan", "mengalirbus": "mengalir bus", "kotordan": "kotor dan", "penumpangbiar": "penumpang biar", "real": "nyata", "ajadan": "saja dan", "dibukadan": "buka dan", "jalandan": "jalan dan", "semuadan": "semua dan",
    "membanyaki": "banyak", "apk": "aplikasi", "adamod": "ada mod", "lamborgini": "lambor begini", "tulis sannya": "tulisan", "aslih": "asli", "bisah": "bisa", "ajasama": "saja sama", "gebenerin": "tidak perbaiki",
    "alus": "halus", "alus pisn": "halus banget", "pokona mah": "pokoknya", "effect": "efek", "airasap": "air asap", "tanahjalan": "tanah jalan", "berlobangkonstruksi": "berlubang konstruksi",
    "jalankecelakaan": "jalan kecelakaan", "kendaraandan": "kendaraan", "mabarnya": "main bareng", "gm": "gim", "birik": "jelek", "bis": "bus", "mantul": "mantap betul", "tualang": "petualang",
    "inidan": "ini dan", "indahjadi": "indah jadi", "beeguna": "berguna", "plisubdate": "tolong perbaiki", "pisssplisss": "tolong", "sumaterabanda": "sumatera banda", "jawatanggerangbandungbekasibandungyogyakarta": "jawa tanggerang bandung bekas bandung yogyakarta",
    "balidenpasar": "bali denpasar", "kalimantanpontianakbanjarmasin": "kalimantan pontianak banjarmasin", "semen tara": "sementara", "kagak": "tidak", "jaladara": "jalan dari", "bengkelkalau": "bengkel kalau",
    "gemnya": "gim", "sukaiini": "suka ini", "anji": "anjing", "ujug ujug": "tiba tiba", "ituterus": "itu terus", "liveryunit": "livery", "jala": "jalan", "didalamtangan": "dalam tangan",
    "nampaktambah": "lihat tambah", "ganenya": "gim", "donlod": "unduh", "updatean": "perbaikan", "sekarangditambah": "sekarang ditambah", "ngalirsmart": "ngalir pintar", "traffickota": "traffic kota",
    "speed": "kecepatan", "traffickota": "traffic kota", "trafficstrobo": "traffic strobo", "lamonganbatutuban": "lamongan batu tuban", "thanks": "terima kasih", "diperbanya": "perbanyak", "mankin": "makin", "memakai": "pakai",
    "dear": "terhormat", "bangmod": "abang mod", "bug": "kesalahan", "btw": "omong omong", "akapgame": "gim", "baguscoba": "bagus coba", "supirnya": "sopir", "tokorumahtoilet": "toko rumah toilet", "rest area": "tempat", "istirahattrmksh": "istirahat terima kasih",
    "sekaliiiiiiiiiiii": "banget", "ngebluurr": "buram", "lagitolong": "lagi tolong", "bank": "abang", "request": "rekomendasi", "tersersh": "terserah", "jateng": "jawa tengah", "prioritasin": "prioritas", "ngebuttan": "ngebut", "nerobos": "terobos",
    "tau": "tahu", "jala": "jalan", "bro": "abang", "nyatapi": "tapi", "saranklo": "saran", "mabartrafficnya": "main bareng traffic", "skill": "kemampuan", "jalananga": "jalan", "pengemudinyaitu": "pengemudi yaitu", "burikk bit": "jelek banget",
    "for": "untuk", "rangin": "reklame", "adalahjalan": "adalah jalan", "barengtolong": "bareng tolong", "please": "tolong", " jawasoale": "jawa soalnya", "agah": "agak", "kekuranggan": "kurang", "nyalip": "salip", "tvrutestikerkap": "tv jalur stiker kap",
    "dibukakecepatan": "buka cepat", "gue": "aku", "jawabali": "jawa bali", "pariwisatagame": "pariwisata gim", "kekuranggan": "kurang", "alhampanjang": "panjang", "graphics": "grafik", "okeee": "oke", "kotanyan": "kota", "riques": "rekomendasi",
    "item": "hitam", "ilangin": "hilangin", "adakansemua": "adakan semua", "terimakasi": "terima kasih", "ashik": "asyik", "bosque": "bos", "mantaaaab": "mantap", "omtambah": "om tambah", "ommakasi": "om terima kasih", "palyer": "pemain",
    "tolonk": "tolong", "membuat": "buat", "modya": "mod", "pejal": "pejalan", "kekurangantrotoar": "kurang trotoar", "sepiga": "sepi", "offroadga": "luar jalan tidak", "modkalau": "mod kalau", "micada": "mikrofon ada", "editoke": "edit oke", "full": "penuh",
    "keretalubangbanjirsama": "kereta lubang banjir sama", "nyasudah": "sudah", "bangen": "banget", "kedepannyaupdate" : "kedepannya perbaiki", "naikturun": "naik turun", "kanankiri": "kanan kiri", "adminadminnya": "admin", "seko": "dari", "malangsby tekan saiki": "malang sampai sekarang",
    "gin": "begitu", "bissa": "bisa", "tuju": "tujuan", "kotakotanya": "kota kota", "start": "pertama", "pilisssssssssssssssssss": "tolong", "tambahinbus": "tambah bus", "barusr": "baru sr", "semuagk": "semua tidak",
    "ci anjur": "cianjur", "nice": "bagus", "toolloongg": "tolong", "bangetya": "banget", "cilacapbandungbekasidan": "cilacap bandung bekasi", "seruuuuuuu": "seru", "nariktapi": "tarik tapi", "terminaltambah": "terminal tambah",
    "pariwisatauntuk": "pariwisata untuk", "tambahditambah": "tambah", "pilnatiudah": "penalti udah", "komplensoaalnya": "komentar soalnya", "gpp vitur": "tidak apa apa fitur", "tambaah": "tambah", "dkk": "dan teman teman",
    "banyaksetelah": "banyak sesudah", "lahuntuk": "untuk", "nglag": "kesalahan", "bogorr": "bogor", "tasikmalayagarutbandung": "tasikmalaya garut bandung", "kotabaru": "kota baru"
}

In [ ]:
def normalize_text(text):
    words = str(text).lower().split()
    normalized_words = []

    for w in words:
        # 1. hapus kata "ya" berdiri sendiri
        if w == "ya":
            continue

        # 2. kamus / manual rules
        if w in kamus:
            normalized_words.append(kamus[w])

        # 3. hapus akhiran "nya" (prioritas)
        elif w.endswith("nya") and w[:-3] in kamus:
            normalized_words.append(kamus[w[:-3]])
        elif w.endswith("nya"):
            normalized_words.append(w[:-3])

        # 4. hapus akhiran "ya"
        elif w.endswith("ya") and len(w) > 2:
            normalized_words.append(w[:-2])

        else:
            normalized_words.append(w)

    return " ".join(normalized_words)

In [ ]:
# Load dataset
df = pd.read_csv('/content/normalisasi.csv')

In [ ]:
df['text_normalized'] = df['normalisasi'].apply(normalize_text)

In [ ]:
df['text_normalized'].to_csv('normalisasiBaru.csv', index=False)